%% test_attribute_specs.m — attributes that carry their own parameters
%
%  preMaetFromAttrTable takes one entry per attribute, either a column name or
%  a struct of that name and the attribute's parameters. Where a role also
%  fixes r or exch, 'orderedMultiset' yields to the analyst with a warning
%  and 'simplex' refuses.
%
%  Mirror of Python tests/test_attribute_specs.py.
%
%  Standalone-runnable; appends to `results` when called from test_mpt.m.

if ~exist('results', 'var')
    results = {};
    standalone = true;
else
    standalone = false;
end

as_demos = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'demos', 'jmm');
as_added = ~contains(path, as_demos);
if as_added; addpath(as_demos); end

as_chorale = gridAttrTable(jmm.bwv347Notes(), 0.25);
as_call = @(varargin) preMaetFromAttrTable(as_chorale, 'time', 'beats', ...
                                       varargin{:});

% --- what an attribute must say --------------------------------------
% A name carries no sigma, so it cannot describe an attribute.
results(end+1, :) = {'attribute specs: a bare name is not an attribute', ...
    throwsErrorWithId(@() as_call('attributes', {'pitch'}), ...
                      'preMaetFromAttrTable:badEntry')}; %#ok<*SAGROW>

results(end+1, :) = {'attribute specs: the attributes are required', ...
    throwsErrorWithId(@() preMaetFromAttrTable(as_chorale, 'time', 'beats'), ...
                      'preMaetFromAttrTable:noAttributes')};

results(end+1, :) = {'attribute specs: every attribute needs a width', ...
    throwsErrorWithId(@() as_call('attributes', {struct('column', 'onset')}), ...
                      'preMaetFromAttrTable:noSigma')};

% Neither r nor exch follows from the score, and neither has an identity:
% r says how many of the chord's values a tuple takes, exch whether their
% order signifies. One value per event determines both, so with
% 'chords', 'separate' neither is asked for.
results(end+1, :) = {'attribute specs: several values at an event need r and exch', ...
    throwsErrorWithId(@() as_call('attributes', ...
        {struct('column', 'pitch', 'sigma', 0.5)}), ...
        'preMaetFromAttrTable:noTupleSize')};

[~, ~, sp] = unpackPreMaet(as_call('attributes', ...
    {struct('column', 'pitch', 'sigma', 0.5)}, 'chords', 'separate'));
results(end+1, :) = {'attribute specs: one value at an event determines r', ...
    sp{1}.r == 1};

[~, ~, sp] = unpackPreMaet(as_call('attributes', { ...
    struct('column', 'pitch', 'name', 'pitchClass', 'sigma', 0.5, ...
           'r', 4, 'exch', false, 'isPer', true, 'period', 12), ...
    struct('column', 'pitch', 'name', 'pitchHeight', 'sigma', 8, ...
           'r', 4, 'exch', false, 'rel', true), ...
    struct('column', 'onset', 'sigma', 0.5)}));
results(end+1, :) = {'attribute specs: an entry carries the attribute''s parameters', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), ...
            {'pitchClass', 'pitchHeight', 'onset'}) ...
    && isequal(cellfun(@(s) s.sigma, sp), [0.5 8 0.5]) ...
    && isequal(cellfun(@(s) s.isPer, sp), [true false false]) ...
    && isequal(cellfun(@(s) s.period, sp), [12 0 0]) ...
    && isequal(cellfun(@(s) s.rel, sp), [false true false])};

% Two attributes of one column under different parameters hold the same
% values, which is what makes pitch class and pitch height readable from
% one pitch column.
[p, ~, sp] = unpackPreMaet(as_call('chords', 'separate', 'attributes', { ...
    struct('column', 'pitch', 'name', 'pitchClass', 'sigma', 0.5, ...
           'isPer', true, 'period', 12), ...
    struct('column', 'pitch', 'name', 'pitchHeight', 'sigma', 8)}));
results(end+1, :) = {'attribute specs: the parameters do not touch the values', ...
    isequaln(p{1}, p{2}) && sp{1}.isPer && ~sp{2}.isPer};

% --- entries that do not make sense --------------------------------------
results(end+1, :) = {'attribute specs: a struct entry needs its column', ...
    throwsErrorWithId(@() preMaetFromAttrTable(as_chorale, 'time', 'beats', ...
        'attributes', {struct('sigma', 0.5)}), ...
        'preMaetFromAttrTable:badEntry')};

results(end+1, :) = {'attribute specs: an unknown parameter is refused', ...
    throwsErrorWithId(@() preMaetFromAttrTable(as_chorale, 'time', 'beats', ...
        'attributes', {struct('column', 'pitch', 'width', 0.5)}), ...
        'preMaetFromAttrTable:badEntry')};

results(end+1, :) = {'attribute specs: periodicity needs a period', ...
    throwsErrorWithId(@() preMaetFromAttrTable(as_chorale, 'time', 'beats', ...
        'attributes', {struct('column', 'pitch', 'isPer', true)}), ...
        'preMaetFromAttrTable:badEntry')};

% --- a role may carry its own attribute's parameters ---------------------
% The simplex role creates an attribute of its own, so its width has
% nowhere else to come from.
[~, ~, sp] = unpackPreMaet(preMaetFromAttrTable(as_chorale, 'time', 'beats', ...
    'attributes', {struct('column', 'pitch', 'sigma', 0.5)}, ...
    'chords', 'separate', ...
    'roles', struct('part', struct('role', 'simplex', 'sigma', 0.2, ...
                                   'name', 'voice')))); %#ok<*ASGLU>
results(end+1, :) = {'attribute specs: a role may carry its attribute''s parameters', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), ...
            {'pitch', 'voice'}) ...
    && sp{2}.sigma == 0.2 && sp{2}.r == 3 && sp{2}.exch == false};

% --- orderedMultiset yields, with a warning ------------------------------
% The role fills the slots; how many are drawn from them is the analyst's
% question, and the article reads this shape at r = 2.
as_w = warning('off', 'preMaetFromAttrTable:tupleSizeOverride');
as_w2 = warning('off', 'preMaetFromAttrTable:orderOverride');
as_restore = onCleanup(@() warning([as_w, as_w2]));

lastwarn('');
[~, ~, sp] = unpackPreMaet(as_call('attributes', ...
    {struct('column', 'pitch', 'sigma', 0.5, 'r', 2)}, ...
    'roles', struct('part', 'orderedMultiset')));
[~, as_id] = lastwarn;
results(end+1, :) = {'attribute specs: orderedMultiset yields the tuple size with a warning', ...
    strcmp(as_id, 'preMaetFromAttrTable:tupleSizeOverride') && sp{1}.r == 2};

lastwarn('');
[~, ~, sp] = unpackPreMaet(as_call('attributes', ...
    {struct('column', 'pitch', 'sigma', 0.5, 'exch', true)}, ...
    'roles', struct('part', 'orderedMultiset')));
[~, as_id] = lastwarn;
results(end+1, :) = {'attribute specs: orderedMultiset yields the order with a warning', ...
    strcmp(as_id, 'preMaetFromAttrTable:orderOverride') && sp{1}.exch == true};

lastwarn('');
[~, ~, sp] = unpackPreMaet(as_call('attributes', ...
    {struct('column', 'pitch', 'sigma', 0.5, 'r', 4, 'exch', false)}, ...
    'roles', struct('part', 'orderedMultiset')));
[~, as_id] = lastwarn;
results(end+1, :) = {'attribute specs: orderedMultiset is silent where the values agree', ...
    isempty(as_id) && sp{1}.r == 4 && sp{1}.exch == false};
clear as_restore

% --- simplex refuses -----------------------------------------------------
% A tuple of some of a point's coordinates is not a point.
results(end+1, :) = {'attribute specs: simplex refuses another tuple size', ...
    throwsErrorWithId(@() preMaetFromAttrTable(as_chorale, 'time', 'beats', ...
        'attributes', {struct('column', 'pitch', 'sigma', 0.5)}, ...
        'chords', 'separate', ...
        'roles', struct('part', struct('role', 'simplex', 'sigma', 0.2, 'r', 2))), ...
        'preMaetFromAttrTable:simplexTupleSize')};

results(end+1, :) = {'attribute specs: simplex refuses an unordered reading', ...
    throwsErrorWithId(@() preMaetFromAttrTable(as_chorale, 'time', 'beats', ...
        'attributes', {struct('column', 'pitch', 'sigma', 0.5)}, ...
        'chords', 'separate', ...
        'roles', struct('part', struct('role', 'simplex', 'sigma', 0.2, 'exch', true))), ...
        'preMaetFromAttrTable:simplexOrder')};

% --- a structural category carries the parameters to every level ---------
[~, ~, sp] = unpackPreMaet(as_call('attributes', ...
    {struct('column', 'pitch', 'name', 'p', 'sigma', 0.5, ...
            'isPer', true, 'period', 12)}, ...
    'roles', struct('part', 'separateAttributes')));
results(end+1, :) = {'attribute specs: separateAttributes carries the parameters to every level', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), ...
            {'p_Soprano', 'p_Alto', 'p_Tenor', 'p_Bass'}) ...
    && all(cellfun(@(s) s.sigma == 0.5 && s.isPer, sp))};

% --- columns the score reader never wrote --------------------------------
% A table that never saw a score: three spatial axes per event.
as_spatial = table([0; 1; 2], [0; 0.5; 1], [1; 1; 1], [0.5; 0.5; 0.5], ...
                   [60; 62; 64], [90; 90; 90], categorical({'V'; 'V'; 'V'}), ...
                   [1; 1; 2], [0; 1; 2], [3; 4; 5], [6; 7; 8], ...
    'VariableNames', {'onsetBeats', 'onsetSeconds', 'durationBeats', ...
                      'durationSeconds', 'pitch', 'velocity', 'part', ...
                      'measure', 'x', 'y', 'z'});
as_axes = {struct('column', 'x', 'sigma', 0.5), ...
           struct('column', 'y', 'sigma', 0.5), ...
           struct('column', 'z', 'sigma', 0.5)};

[p, ~, sp] = unpackPreMaet(preMaetFromAttrTable(as_spatial, 'time', 'beats', ...
    'chords', 'separate', 'attributes', as_axes));
results(end+1, :) = {'attribute specs: any column may be an attribute', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), {'x', 'y', 'z'}) ...
    && isequal(p{1}, [0 1 2])};

% The whole path: an arbitrary table converts, and the axes that describe
% one position become one attribute read whole.
[p, ~, sp] = unpackPreMaet(bindAttributes(preMaetFromAttrTable(as_spatial, ...
    'time', 'beats', 'chords', 'separate', 'attributes', as_axes), ...
    {'x', 'y', 'z'}, 'name', 'position', 'r', 3, 'exch', false));
results(end+1, :) = {'attribute specs: arbitrary columns bind into one position', ...
    numel(p) == 1 && isequal(size(p{1}), [3 3]) ...
    && isequal(p{1}(:, 1).', [0 3 6]) && sp{1}.sigma == 0.5};

results(end+1, :) = {'attribute specs: an absent column is not an attribute', ...
    throwsErrorWithId(@() preMaetFromAttrTable(as_spatial, 'time', 'beats', ...
        'attributes', {struct('column', 'w', 'sigma', 0.5)}), ...
        'preMaetFromAttrTable:attribute')};

% A categorical column belongs to 'roles', which says how a category
% reaches the pre-MAET; the supplement's unrolled grammar encoding is a
% label attribute on its own simplex.
as_spatial.rule = categorical({'V_I'; 'Repeat'; 'V_I'});
results(end+1, :) = {'attribute specs: a categorical column is sent to the roles', ...
    throwsErrorWithId(@() preMaetFromAttrTable(as_spatial, 'time', 'beats', ...
        'attributes', {struct('column', 'rule', 'sigma', 0.5)}), ...
        'preMaetFromAttrTable:categoricalAttribute')};

[~, ~, sp] = unpackPreMaet(preMaetFromAttrTable(as_spatial, 'time', 'beats', ...
    'chords', 'separate', ...
    'attributes', {struct('column', 'x', 'sigma', 0.5)}, ...
    'roles', struct('rule', struct('role', 'simplex', 'sigma', 0.1))));
results(end+1, :) = {'attribute specs: a category reaches the pre-MAET by its role', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), {'x', 'rule'}) ...
    && sp{2}.sigma == 0.1};

if as_added; rmpath(as_demos); end

if standalone
    nPass = sum([results{:, 2}]);
    fprintf('\n=== test_attribute_specs: %d passed, %d failed (of %d) ===\n', ...
            nPass, size(results, 1) - nPass, size(results, 1));
end
