%% test_grid_events.m — sampling an event table on a grid
%
%  The acceptance case is Analysis 1.1 of the JMM article, which samples
%  BWV 347 on a sixteenth-note grid: N = 272 events, held notes
%  replicating across the points they occupy, and no rests.
%
%  Mirror of Python tests/test_grid_events.py. Grid positions and note
%  identifiers are 1-based here and 0-based there, each idiomatic.
%
%  Standalone-runnable; appends to `results` when called from test_mpt.m.

if ~exist('results', 'var')
    results = {};
    standalone = true;
else
    standalone = false;
end
ge_tol = 1e-12;

% Two notes far enough apart that the grid has empty points.
ge_gapped = table([0; 3], [0; 1.5], [1; 1], [0.5; 0.5], [60; 64], ...
                  [90; 90], categorical({'A'; 'A'}, {'A', 'B'}), ...
                  [1; 1], [1; 1], [false; true], ...
                  'VariableNames', {'onsetBeats', 'onsetSeconds', ...
                  'durationBeats', 'durationSeconds', 'pitch', ...
                  'velocity', 'part', 'voice', 'measure', 'fermata'});

% One note of four beats and one of one, so replication is visible.
ge_held = table([0; 0], [0; 0], [4; 1], [2; 0.5], [60; 67], [90; 90], ...
                categorical({'A'; 'B'}, {'A', 'B'}), [1; 1], [1; 1], ...
                [false; false], ...
                'VariableNames', {'onsetBeats', 'onsetSeconds', ...
                'durationBeats', 'durationSeconds', 'pitch', ...
                'velocity', 'part', 'voice', 'measure', 'fermata'});

% --- the acceptance case -------------------------------------------------
ge_demos = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'demos', 'jmm');
ge_added = ~contains(path, ge_demos);
if ge_added; addpath(ge_demos); end
ge_notes = jmm.bwv347Notes();
ge_bwv = gridEvents(ge_notes, 0.25);
results(end+1, :) = {'grid: BWV 347 gives the manuscript grid (N = 272)', ...
    numel(unique(ge_bwv.gridIndex)) == 272 ...
    && height(ge_bwv) == 272 * 4 ...
    && ~any(isnan(ge_bwv.noteId))}; %#ok<*SAGROW>

% --- replication and occupancy ------------------------------------------
ge_g = gridEvents(ge_held, 1);
ge_long  = ge_g(ge_g.noteId == 1, :);
ge_short = ge_g(ge_g.noteId == 2, :);
results(end+1, :) = {'grid: a held note replicates across the points it covers', ...
    height(ge_long) == 4 && height(ge_short) == 1 ...
    && isequal(ge_long.gridIndex(:).', 1:4)};

% Occupancy is half-open, so the note's end is the next note's point.
results(end+1, :) = {'grid: a note ending on a grid point does not occupy it', ...
    ~ismember(2, ge_short.gridIndex)};

results(end+1, :) = {'grid: duration still means the note''s own duration', ...
    all(ge_long.durationBeats == 4)};

% --- empty grid points ---------------------------------------------------
ge_gap = gridEvents(ge_gapped, 1);
ge_empty = ge_gap(isnan(ge_gap.noteId), :);
results(end+1, :) = {'grid: an empty point is a row with its note columns missing', ...
    height(ge_empty) == 2 && isequal(ge_empty.gridIndex(:).', [2 3]) ...
    && isequal(ge_empty.gridOnsetBeats(:).', [1 2]) ...
    && all(isnan(ge_empty.pitch)) && all(isnan(ge_empty.velocity)) ...
    && all(isnan(ge_empty.measure)) && all(isnan(ge_empty.fermata)) ...
    && all(isundefined(ge_empty.part))};

[ge_p, ge_w] = unpackPreMaet(preMaetFromScore(ge_gap, ...
    'attributes', {'pitch'}, 'weights', 'weight', 'time', 'beats'));
results(end+1, :) = {'grid: empty points survive into a pre-MAET as events with no value', ...
    all(isnan(ge_p{1}(1, [2 3]))) && all(ge_w{1}(1, [2 3]) == 0)};

% --- weight policies -----------------------------------------------------
ge_item = gridEvents(ge_notes, 0.25, 'weights', 'item');
results(end+1, :) = {'grid: item weighting makes each note count once', ...
    abs(sum(ge_item.weight) - height(ge_notes)) < 1e-9};

% One note of a beat and a half, so it fills one slice and half of the
% next, and the three policies disagree.
ge_straddle = table(0, 0, 1.5, 0.75, 60, 90, categorical({'A'}, {'A'}), ...
                    1, 1, false, ...
                    'VariableNames', {'onsetBeats', 'onsetSeconds', ...
                    'durationBeats', 'durationSeconds', 'pitch', ...
                    'velocity', 'part', 'voice', 'measure', 'fermata'});
ge_pol = @(w) gridEvents(ge_straddle, 1, 'weights', w).weight(:).';
results(end+1, :) = {'grid: the three policies on a straddling note', ...
    max(abs(ge_pol('presence') - [1 1])) < ge_tol ...
    && max(abs(ge_pol('coverage') - [1 0.5])) < ge_tol ...
    && max(abs(ge_pol('item') - [2/3 1/3])) < 1e-12};

results(end+1, :) = {'grid: coverage is the default', ...
    max(abs(gridEvents(ge_straddle, 1).weight(:).' - [1 0.5])) < ge_tol};

results(end+1, :) = {'grid: presence counts a note once per slice it sounds in', ...
    abs(sum(gridEvents(ge_held, 1, 'weights', 'presence').weight) - 5) < ge_tol};

% A note falling between two grid points still overlaps a slice, so
% nothing disappears for being short.
ge_short = ge_straddle;
ge_short.onsetBeats = 0.25;
ge_short.durationBeats = 0.25;
ge_shortW = @(w) gridEvents(ge_short, 1, 'weights', w, 'limits', [0 1]).weight;
results(end+1, :) = {'grid: a note shorter than the step is not lost', ...
    abs(ge_shortW('presence') - 1) < ge_tol ...
    && abs(ge_shortW('coverage') - 0.25) < ge_tol ...
    && abs(ge_shortW('item') - 1) < ge_tol};

% The kernel is linear in weight, so splitting a note's weight over the
% points it covers leaves the density unchanged.
ge_density = @(pm) buildMaet(pm.pAttr, pm.wAttr, 50, 1, false, false, 0, ...
                             'verbose', false);
ge_un = ge_density(preMaetFromScore(ge_notes, 'attributes', {'pitch'}, ...
    'chords', 'separate', 'weights', 'ones', 'time', 'beats'));
ge_gr = ge_density(preMaetFromScore(ge_item, 'attributes', {'pitch'}, ...
    'weights', 'weight', 'time', 'beats'));
ge_qv = evalMaet(ge_un, {64}, 'verbose', false);
results(end+1, :) = {'grid: item weighting reproduces the ungridded density at r = 1', ...
    abs(evalMaet(ge_gr, {64}, 'verbose', false) - ge_qv) < 1e-9 * abs(ge_qv)};

% --- the grid specification ---------------------------------------------
results(end+1, :) = {'grid: it runs from zero to the last note''s end by default', ...
    abs(max(ge_gap.gridOnsetBeats) - 3) < ge_tol};

ge_lim = gridEvents(ge_gapped, 1, 'limits', [0 2]);
results(end+1, :) = {'grid: limits override the extent', ...
    numel(unique(ge_lim.gridIndex)) == 2};

ge_secs = gridEvents(ge_gapped, 0.5, 'time', 'seconds');
results(end+1, :) = {'grid: a seconds grid uses the seconds columns', ...
    any(strcmp(ge_secs.Properties.VariableNames, 'gridOnsetSeconds')) ...
    && numel(unique(ge_secs.gridIndex)) == 4};

ge_noSecs = removevars(ge_gapped, {'onsetSeconds', 'durationSeconds'});
results(end+1, :) = {'grid: gridding over a missing time base says so', ...
    errorMessageContains(@() gridEvents(ge_noSecs, 1, 'time', 'seconds'), ...
                         'beat map')};

ge_sounding = ge_gapped;
ge_sounding.soundingDurationBeats = [3; 1];
results(end+1, :) = {'grid: the sounding duration may define occupancy', ...
    ~any(isnan(gridEvents(ge_sounding, 1, 'duration', 'soundingDuration').noteId))};

results(end+1, :) = {'grid: the step must be positive and finite', ...
    throwsErrorWithId(@() gridEvents(ge_gapped, 0), 'gridEvents:step') ...
    && throwsErrorWithId(@() gridEvents(ge_gapped, -1), 'gridEvents:step') ...
    && throwsErrorWithId(@() gridEvents(ge_gapped, Inf), 'gridEvents:step')};

ge_meta = ge_gap.Properties.UserData;
results(end+1, :) = {'grid: the result records that it is gridded', ...
    strcmp(ge_meta.granularity, 'grid') && ge_meta.gridStep == 1 ...
    && strcmp(ge_meta.gridTime, 'beats')};

if ge_added; rmpath(ge_demos); end

if standalone
    nPass = sum([results{:, 2}]);
    fprintf('\n=== test_grid_events: %d passed, %d failed (of %d) ===\n', ...
            nPass, size(results, 1) - nPass, size(results, 1));
end
