%% test_bind_attributes.m — binding along the attribute axis, and its inverse
%
%  bindAttributes gathers several attributes into one whose value at an
%  event is the tuple of all of them; separateAttributes splits one back
%  into a slot apiece. The two are inverse, and the second is also the
%  operation by which the conversion's two structural roles differ.
%
%  Mirror of Python tests/test_bind_attributes.py.
%
%  Standalone-runnable; appends to `results` when called from test_mpt.m.

if ~exist('results', 'var')
    results = {};
    standalone = true;
else
    standalone = false;
end

% Three spatial axes of one position, as three attributes.
ba_p = {[1 2 3], [4 5 6], [7 8 9]};
ba_specs = cell(1, 3);
ba_names = {'x', 'y', 'z'};
for ba_i = 1:3
    ba_specs{ba_i} = struct('name', ba_names{ba_i}, 'r', 1, 'exch', true, ...
                            'sigma', 0.5, 'rel', false, 'isPer', false, ...
                            'period', 0);
end
ba_axes = packPreMaet(ba_p, [], ba_specs);

% --- binding --------------------------------------------------------------
[p, ~, sp] = unpackPreMaet(bindAttributes(ba_axes, {'x', 'y', 'z'}, ...
    'name', 'position', 'r', 3, 'exch', false));
results(end+1, :) = {'bindAttributes: stacks the values in the order given', ...
    numel(p) == 1 && isequal(size(p{1}), [3 3]) ...
    && isequal(p{1}(:, 1).', [1 4 7]) ...
    && strcmp(sp{1}.name, 'position') && sp{1}.r == 3 ...
    && sp{1}.exch == false}; %#ok<*SAGROW>

[p, ~, ~] = unpackPreMaet(bindAttributes(ba_axes, {'z', 'x', 'y'}, ...
    'name', 'position', 'r', 3, 'exch', false));
results(end+1, :) = {'bindAttributes: the order listed is the order bound', ...
    isequal(p{1}(:, 1).', [7 1 4])};

[p, ~, sp] = unpackPreMaet(bindAttributes(ba_axes, {'y', 'z'}, ...
    'name', 'yz', 'r', 2, 'exch', false));
results(end+1, :) = {'bindAttributes: the bound attribute takes the place of the first', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), {'x', 'yz'}) ...
    && isequal(size(p{1}), [1 3]) && isequal(size(p{2}), [2 3])};

[~, ~, sp] = unpackPreMaet(bindAttributes(ba_axes, {'x', 'y'}, ...
    'name', 'xy', 'r', 2, 'exch', false));
results(end+1, :) = {'bindAttributes: agreed parameters are inherited', ...
    sp{1}.sigma == 0.5 && sp{1}.isPer == false};

ba_mixedSpecs = ba_specs;
ba_mixedSpecs{2}.sigma = 2;
ba_mixed = packPreMaet(ba_p, [], ba_mixedSpecs);
results(end+1, :) = {'bindAttributes: disagreeing parameters are refused', ...
    throwsErrorWithId(@() bindAttributes(ba_mixed, {'x', 'y'}, ...
        'name', 'xy', 'r', 2, 'exch', false), 'bindAttributes:disagree')};

[~, ~, sp] = unpackPreMaet(bindAttributes(ba_mixed, {'x', 'y'}, ...
    'name', 'xy', 'r', 2, 'exch', false, 'sigma', 1));
results(end+1, :) = {'bindAttributes: a disagreement is settled by the call', ...
    sp{1}.sigma == 1};

% Neither r nor exch follows from the inputs, and neither has an identity.
results(end+1, :) = {'bindAttributes: the bound attribute needs r and exch', ...
    throwsErrorWithId(@() bindAttributes(ba_axes, {'x', 'y'}, 'name', 'xy'), ...
        'bindAttributes:noTupleSize')};

results(end+1, :) = {'bindAttributes: the bound attribute needs a name', ...
    throwsErrorWithId(@() bindAttributes(ba_axes, {'x', 'y'}, ...
        'r', 2, 'exch', false), 'bindAttributes:noName')};

results(end+1, :) = {'bindAttributes: binding one attribute is refused', ...
    throwsErrorWithId(@() bindAttributes(ba_axes, {'x'}, ...
        'name', 'xx', 'r', 1, 'exch', false), 'bindAttributes:oneAttribute')};

results(end+1, :) = {'bindAttributes: an attribute cannot be bound to itself', ...
    throwsErrorWithId(@() bindAttributes(ba_axes, {'x', 'x'}, ...
        'name', 'xx', 'r', 2, 'exch', false), 'bindAttributes:repeated')};

ba_w = {ones(1, 3), 2 * ones(1, 3), 3 * ones(1, 3)};
[~, w, ~] = unpackPreMaet(bindAttributes(packPreMaet(ba_p, ba_w, ba_specs), ...
    {'x', 'y', 'z'}, 'name', 'position', 'r', 3, 'exch', false));
results(end+1, :) = {'bindAttributes: weights follow their values', ...
    isequal(w{1}(:, 1).', [1 2 3])};

% --- separating -----------------------------------------------------------
ba_bound = bindAttributes(ba_axes, {'x', 'y', 'z'}, 'name', 'position', ...
                          'r', 3, 'exch', false);
[p, ~, sp] = unpackPreMaet(separateAttributes(ba_bound, 'position'));
results(end+1, :) = {'separateAttributes: separating undoes binding', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), ...
            {'position_1', 'position_2', 'position_3'}) ...
    && isequal(p, ba_p)};

ba_bound2 = bindAttributes(ba_axes, {'x', 'y'}, 'name', 'xy', 'r', 2, ...
    'exch', false, 'sigma', 3, 'isPer', true, 'period', 12);
[~, ~, sp] = unpackPreMaet(separateAttributes(ba_bound2, 'xy'));
results(end+1, :) = {'separateAttributes: the parts carry the source''s kernel', ...
    all(cellfun(@(s) s.sigma == 3 && s.isPer && s.period == 12 ...
                     && s.r == 1 && s.exch == true, sp(1:2)))};

[~, ~, sp] = unpackPreMaet(separateAttributes(ba_bound2, 'xy', ...
    'names', {'left', 'right'}));
results(end+1, :) = {'separateAttributes: the parts may be named', ...
    isequal(cellfun(@(s) s.name, sp(1:2), 'UniformOutput', false), ...
            {'left', 'right'})};

results(end+1, :) = {'separateAttributes: a single-valued attribute is refused', ...
    throwsErrorWithId(@() separateAttributes(ba_axes, 'x'), ...
        'separateAttributes:nothingToSeparate')};

% --- the two structural roles differ by this operation --------------------
% Under 'orderedMultiset' slot k is level k, so splitting that attribute
% slot by slot is what 'separateAttributes' builds from the table -- up to
% the names, which only the table carries.
ba_demos = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'demos', 'jmm');
ba_added = ~contains(path, ba_demos);
if ba_added; addpath(ba_demos); end

ba_chorale = gridAttrTable(jmm.bwv347Notes(), 0.25);
ba_attr = {struct('column', 'pitch', 'sigma', 0.5)};
[pRole, ~, spRole] = unpackPreMaet(preMaetFromAttrTable(ba_chorale, ...
    'attributes', ba_attr, 'time', 'beats', ...
    'roles', struct('part', 'separateAttributes')));
[pOp, ~, spOp] = unpackPreMaet(separateAttributes(preMaetFromAttrTable( ...
    ba_chorale, 'attributes', ba_attr, 'time', 'beats', ...
    'roles', struct('part', 'orderedMultiset')), 'pitch'));
results(end+1, :) = {'separateAttributes: the two structural roles differ by this operation', ...
    numel(pOp) == 4 && numel(pRole) == 4 && isequaln(pRole, pOp) ...
    && isequal(cellfun(@(s) s.r, spRole), cellfun(@(s) s.r, spOp)) ...
    && isequal(cellfun(@(s) s.exch, spRole), cellfun(@(s) s.exch, spOp)) ...
    && isequal(cellfun(@(s) s.sigma, spRole), cellfun(@(s) s.sigma, spOp))};

if ba_added; rmpath(ba_demos); end

% --- the point of binding -------------------------------------------------
% The density reads the tuple, not the product of three attributes.
ba_d = buildMaet(ba_bound, 'verbose', false);
results(end+1, :) = {'bindAttributes: a bound attribute builds', ...
    abs(simMaet(ba_d, ba_d, 'verbose', false) - 1) < 1e-12};

if standalone
    nPass = sum([results{:, 2}]);
    fprintf('\n=== test_bind_attributes: %d passed, %d failed (of %d) ===\n', ...
            nPass, size(results, 1) - nPass, size(results, 1));
end
