%% test_pre_maet_roles.m — how a categorical column reaches the pre-MAET
%
%  The three encodings the JMM article contrasts on BWV 347's voicing
%  (Analysis 1.2): voice-aware, where the level is a position in an
%  ordered multiset; voice-agnostic, where it is not encoded at all; and
%  simplex-voice, where it is a vertex value on its own attribute and each
%  note is its own event.
%
%  Mirror of Python tests/test_pre_maet_roles.py.
%
%  Standalone-runnable; appends to `results` when called from test_mpt.m.

if ~exist('results', 'var')
    results = {};
    standalone = true;
else
    standalone = false;
end
pr_tol = 1e-12;

pr_demos = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'demos', 'jmm');
pr_added = ~contains(path, pr_demos);
if pr_added; addpath(pr_demos); end

% BWV 347 on the sixteenth grid, so every event holds all four voices and
% the structural roles have a full slot per level.
pr_notes = jmm.bwv347Notes();
pr_chorale = gridAttrTable(pr_notes, 0.25);
% A structural role fixes r and exch, so the role cases leave them out;
% without a role the chord's four values need both, since neither follows
% from the score.
pr_attr = {struct('column', 'pitch', 'sigma', 1)};
pr_attrPlain = {struct('column', 'pitch', 'sigma', 1, 'r', 1, 'exch', true)};
pr_pm = @(attrs, varargin) unpackPreMaet(preMaetFromAttrTable(pr_chorale, ...
    'attributes', attrs, 'time', 'beats', varargin{:}));

% --- the three encodings -------------------------------------------------
[p, ~, sp] = pr_pm(pr_attr, 'roles', struct('part', 'orderedMultiset'));
results(end+1, :) = {'roles: ordered multiset puts each voice in its own position', ...
    numel(p) == 1 && isequal(size(p{1}), [4 272]) && sp{1}.r == 4 ...
    && sp{1}.exch == false && isequal(p{1}(:, 1).', [69 64 61 57])}; %#ok<*SAGROW>

[p, ~, sp] = pr_pm(pr_attr, 'roles', struct('part', 'separateAttributes'));
results(end+1, :) = {'roles: separate attributes gives one attribute per voice', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), ...
            {'pitch_Soprano', 'pitch_Alto', 'pitch_Tenor', 'pitch_Bass'}) ...
    && isequal(cellfun(@(m) m(1, 1), p), [69 64 61 57])};

[p, ~, sp] = unpackPreMaet(preMaetFromAttrTable(pr_chorale, ...
    'attributes', { ...
        struct('column', 'pitch', 'sigma', 1)}, ...
        'time', 'beats', 'chords', 'separate', ...
    'roles', struct('part', struct('role', 'simplex', 'sigma', 1))));
pr_vert = simplexVertices(4);
results(end+1, :) = {'roles: simplex tags each note with its voice vertex', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), {'pitch', 'part'}) ...
    && size(p{2}, 1) == 3 && sp{2}.r == 3 && sp{2}.exch == false ...
    && max(abs(p{2}(:, 1:4).' - pr_vert), [], 'all') < pr_tol};

[p, ~, sp] = pr_pm(pr_attrPlain);
results(end+1, :) = {'roles: no role leaves the chord an unordered multiset', ...
    isequal(size(p{1}), [4 272]) && sp{1}.r == 1 && sp{1}.exch == true};

pDrop = pr_pm(pr_attrPlain, 'roles', struct('part', 'drop'));
results(end+1, :) = {'roles: drop is the same as no role', isequaln(pDrop{1}, p{1})};

% --- what a structural category does and does not split ------------------
[~, ~, sp] = unpackPreMaet(preMaetFromAttrTable(pr_chorale, ...
    'attributes', { ...
        struct('column', 'pitch', 'sigma', 1), ...
        struct('column', 'velocity', 'sigma', 1)}, ...
        'time', 'beats', ...
    'roles', struct('part', 'separateAttributes')));
results(end+1, :) = {'roles: a structural category splits every per-note attribute', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), ...
            {'pitch_Soprano', 'pitch_Alto', 'pitch_Tenor', 'pitch_Bass', ...
             'velocity_Soprano', 'velocity_Alto', 'velocity_Tenor', 'velocity_Bass'})};

% The notes gathered into one event share an onset and a bar, so
% splitting either would give one attribute per voice carrying the same
% number, raised to the fourth by the product across attributes.
pr_evOk = true;
for pr_ev = {'onset', 'measure'}
    [p, ~, sp] = unpackPreMaet(preMaetFromAttrTable(pr_chorale, ...
        'attributes', {struct('column', 'pitch', 'sigma', 1), ...
                       struct('column', pr_ev{1}, 'sigma', 1)}, ...
        'time', 'beats', ...
        'roles', struct('part', 'orderedMultiset')));
    pr_evOk = pr_evOk ...
        && isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), ...
                   [{'pitch'}, pr_ev]) ...
        && isequal(size(p{2}), [1 272]) && sp{2}.r == 1;
end
results(end+1, :) = {'roles: event-level attributes are not split', pr_evOk};

pr_reg = pr_chorale;
pr_reg.register = categorical(repmat({'low'}, height(pr_reg), 1), {'low', 'high'});
pr_reg.register(pr_reg.pitch > 64) = 'high';
[~, ~, sp] = unpackPreMaet(preMaetFromAttrTable(pr_reg, ...
    'attributes', {struct('column', 'pitch', 'sigma', 1)}, 'time', 'beats', ...
    'roles', struct('part', 'orderedMultiset', 'register', struct('role', 'simplex', 'sigma', 1))));
results(end+1, :) = {'roles: a simplex category is tagged within each structural slot', ...
    isequal(cellfun(@(s) s.name, sp, 'UniformOutput', false), ...
            {'pitch', 'register_Soprano', 'register_Alto', ...
             'register_Tenor', 'register_Bass'}) ...
    && all(cellfun(@(s) s.r, sp(2:end)) == 1)};

% --- the event key -------------------------------------------------------
[p, ~, ~] = unpackPreMaet(preMaetFromAttrTable(pr_chorale, ...
    'attributes', { ...
        struct('column', 'pitch', 'sigma', 1, 'r', 1, 'exch', true), ...
        struct('column', 'onset', 'sigma', 1, 'r', 1, 'exch', true)}, ...
        'time', 'beats'));
results(end+1, :) = {'roles: a gridded table takes its onset from the grid', ...
    max(abs(p{2}(1, 1:4) - [0 0.25 0.5 0.75])) < pr_tol};

% The grid steps in beats; its points have a time in both, so the onset
% attribute may be read on a clock -- which is what a sigma in
% milliseconds over metrical slices needs.
pr_bothAttr = {struct('column', 'pitch', 'sigma', 1, 'r', 1, 'exch', true), ...
               struct('column', 'onset', 'sigma', 1, 'r', 1, 'exch', true)};
[pBeats, ~, ~] = unpackPreMaet(preMaetFromAttrTable(pr_chorale, ...
    'attributes', pr_bothAttr, 'time', 'beats'));
[pSecs, ~, ~] = unpackPreMaet(preMaetFromAttrTable(pr_chorale, ...
    'attributes', pr_bothAttr, 'time', 'seconds'));
results(end+1, :) = {'roles: a beat grid reads its onset in either unit', ...
    max(abs(pBeats{2}(1, 1:4) - [0 0.25 0.5 0.75])) < pr_tol ...
    && max(abs(pSecs{2}(1, 1:4) - [0 0.125 0.25 0.375])) < pr_tol};

pr_meas = double(pr_chorale.measure);
pr_runs = 1 + sum(pr_meas(2:end) ~= pr_meas(1:end-1));
[p, ~, ~] = unpackPreMaet(preMaetFromAttrTable(pr_chorale, ...
    'attributes', { ...
        struct('column', 'pitch', 'sigma', 1, 'r', 1, 'exch', true)}, ...
        'time', 'beats', 'groupBy', 'measure'));
results(end+1, :) = {'roles: groupBy names the event key (contiguous runs)', ...
    size(p{1}, 2) == pr_runs && pr_runs > numel(unique(pr_meas))};

% --- refusals and the warning -------------------------------------------
results(end+1, :) = {'roles: two structural categories are refused', ...
    throwsErrorWithId(@() preMaetFromAttrTable(pr_reg, 'attributes', { ...
        struct('column', 'pitch', 'sigma', 1)}, ...
        'time', 'beats', 'roles', struct('part', 'orderedMultiset', ...
        'register', 'separateAttributes')), 'preMaetFromAttrTable:twoStructural')};

results(end+1, :) = {'roles: simplex alone needs one event per note', ...
    throwsErrorWithId(@() preMaetFromAttrTable(pr_chorale, 'attributes', { ...
        struct('column', 'pitch', 'sigma', 1)}, ...
        'time', 'beats', 'roles', struct('part', struct('role', 'simplex', 'sigma', 1))), ...
        'preMaetFromAttrTable:simplexNeedsSeparate')};

results(end+1, :) = {'roles: a structural role needs bound events', ...
    throwsErrorWithId(@() preMaetFromAttrTable(pr_chorale, 'attributes', { ...
        struct('column', 'pitch', 'sigma', 1)}, ...
        'time', 'beats', 'chords', 'separate', ...
        'roles', struct('part', 'orderedMultiset')), ...
        'preMaetFromAttrTable:structuralNeedsBind')};

results(end+1, :) = {'roles: a role needs a categorical column', ...
    throwsErrorWithId(@() preMaetFromAttrTable(pr_chorale, 'attributes', { ...
        struct('column', 'pitch', 'sigma', 1)}, ...
        'time', 'beats', 'roles', struct('pitch', 'simplex')), ...
        'preMaetFromAttrTable:roleKind')};

results(end+1, :) = {'roles: an unknown role is refused', ...
    throwsErrorWithId(@() preMaetFromAttrTable(pr_chorale, 'attributes', { ...
        struct('column', 'pitch', 'sigma', 1)}, ...
        'time', 'beats', 'roles', struct('part', 'split')), ...
        'preMaetFromAttrTable:unknownRole')};

% Binding the ungridded chorale by onset leaves many events without all
% four voices, since the parts do not all move together.
pr_w = warning('off', 'preMaetFromAttrTable:incompleteEvents');
pr_restore = onCleanup(@() warning(pr_w));
lastwarn('');
[p, ~, ~] = unpackPreMaet(preMaetFromAttrTable(pr_notes, ...
    'attributes', {struct('column', 'pitch', 'sigma', 1)}, 'time', 'beats', ...
    'roles', struct('part', 'orderedMultiset')));
[~, pr_id] = lastwarn;
results(end+1, :) = {'roles: an event missing a level is dropped with a warning', ...
    strcmp(pr_id, 'preMaetFromAttrTable:incompleteEvents') ...
    && size(p{1}, 1) == 4 && size(p{1}, 2) < 102 && ~any(isnan(p{1}), 'all')};
clear pr_restore

if pr_added; rmpath(pr_demos); end

if standalone
    nPass = sum([results{:, 2}]);
    fprintf('\n=== test_pre_maet_roles: %d passed, %d failed (of %d) ===\n', ...
            nPass, size(results, 1) - nPass, size(results, 1));
end
