%% test_massMaet.m — the mass of a density in a region
%
%  massMaet's closed forms are pinned to numerical integrals of the
%  density evalMaet returns under 'gaussian' (kernels of unit mass,
%  untruncated); sweptMass is pinned to the composition it stands for
%  (weightEvents -> buildMaet -> massMaet); and the values shared with
%  Python's tests/test_mass_maet.py are pinned to 1e-12. Mirror of that
%  file.
%
%  Standalone-runnable; appends to `results` when called from test_mpt.m.

if ~exist('results', 'var')
    results = {};
    standalone = true;
    addpath(fileparts(mfilename('fullpath')));
    clear cleanupDefaults
    cleanupDefaults = mptTestIsolateDefaults(); %#ok<NASGU>
else
    standalone = false;
end
prevHints = mptDefaults('showHints', false);

pM = {[60; 64; 67]};
wM = {[1; 0.5; 2]};
flatM = @(sigma, r, rel, per, period, varargin) buildMaet(pM, wM, sigma, r, ...
    rel, per, period, varargin{:}, 'verbose', false);
evM = @(d, X) evalMaet(d, X, 'gaussian', 'truncationSigmas', Inf, ...
    'verbose', false);
f1M = @(d) @(x) reshape(evM(d, x(:).'), size(x));
f2M = @(d) @(x, y) reshape(evM(d, [x(:).'; y(:).']), size(x));
closeM = @(a, b, tol) abs(a - b) <= tol;

% ---- totals -----------------------------------------------------------------
results(end+1, :) = {'massMaet total is the sum of weight products', ...
    closeM(massMaet(flatM(1, 1, false, false, 0)), 3.5, 1e-13) ...
    && closeM(massMaet(flatM(1, 2, false, false, 0)), 7, 1e-13) ...
    && closeM(massMaet(flatM(1, 2, true, false, 0)), 7, 1e-13) ...
    && closeM(massMaet(flatM(1, 2, true, false, 0), 'normalize', 'total'), 1, 1e-14)}; %#ok<SAGROW>

% ---- boxes ------------------------------------------------------------------
d = flatM(1, 1, false, false, 0);
results(end+1, :) = {'massMaet box, absolute r = 1', ...
    closeM(massMaet(d, 'region', {1, [61 66]}), integral(f1M(d), 61, 66, ...
    'AbsTol', 1e-13), 1e-10)}; %#ok<SAGROW>

d = flatM(1, 2, false, false, 0);
results(end+1, :) = {'massMaet box, absolute r = 2, a row per coordinate', ...
    closeM(massMaet(d, 'region', {1, [59 62; 63 70]}), ...
    integral2(f2M(d), 59, 62, 63, 70, 'AbsTol', 1e-12), 1e-8)}; %#ok<SAGROW>

d = flatM(1, 2, true, false, 0);
results(end+1, :) = {'massMaet box, relative dyads (interval band, both signs)', ...
    closeM(massMaet(d, 'region', {1, [2 5]}), integral(f1M(d), 2, 5, ...
    'AbsTol', 1e-13), 1e-10) ...
    && closeM(massMaet(d, 'region', {1, [-5 -2]}), ...
    massMaet(d, 'region', {1, [2 5]}), 1e-12)}; %#ok<SAGROW>

d = flatM(2.5, 1, false, true, 12);
results(end+1, :) = {'massMaet box, periodic full-image (and wrapping bounds)', ...
    closeM(massMaet(d, 'region', {1, [10 17]}), integral(f1M(d), 10, 17, ...
    'AbsTol', 1e-13), 1e-10) ...
    && closeM(massMaet(d, 'region', {1, [0 12]}), 3.5, 1e-12) ...
    && closeM(massMaet(d, 'region', {1, [10 17]}), ...
    massMaet(d, 'region', {1, [-2 5]}), 1e-12)}; %#ok<SAGROW>

warning('off', 'buildMaet:absPerSingleImage');
d = flatM(2.5, 1, false, true, 12, 'wrap', 'single-image');
cutM = 1 - erfc(6 / 2.5 / sqrt(2));
% The single-image kernel has a kink at each centre's antipode (13 here,
% the antipode of 67 mod 12), so the quadrature is split there and held to
% a tight relative tolerance; integral's default RelTol (1e-6) leaves an
% error of about 4e-8 across the kink.
results(end+1, :) = {'massMaet box, periodic single-image (renormalized)', ...
    closeM(massMaet(d, 'region', {1, [10 17]}), integral(f1M(d), 10, 17, ...
    'AbsTol', 1e-13, 'RelTol', 1e-12, 'Waypoints', 13) / cutM, 1e-10) ...
    && closeM(massMaet(d, 'region', {1, [3 15]}), 3.5, 1e-12)}; %#ok<SAGROW>

% ---- Gaussian regions ---------------------------------------------------------
d = flatM(1, 1, false, false, 0);
fd = f1M(d);
results(end+1, :) = {'massMaet Gaussian region, absolute', ...
    closeM(massMaet(d, 'region', {1, {'gaussian', 63, 1.5}}), ...
    integral(@(x) fd(x) .* exp(-(x - 63).^2 / 4.5), 40, 90, ...
    'AbsTol', 1e-13), 1e-10)}; %#ok<SAGROW>

d = buildMaet({[0; 3; 7; 10]}, [], 1, 3, true, false, 0, 'verbose', false);
fd = f2M(d);
gM = @(x, y) fd(x, y) .* exp(-((x - 3).^2 + (y - 7).^2) / (2 * 1.2^2));
results(end+1, :) = {'massMaet Gaussian region, correlated relative coordinates', ...
    closeM(massMaet(d, 'region', {1, {'gaussian', [3 7], 1.2}}), ...
    integral2(gM, -5, 12, -5, 15, 'AbsTol', 1e-12), 1e-7)}; %#ok<SAGROW>

% ---- several attributes -------------------------------------------------------
d = buildMaet({[60 62 64 65], [0 1 2 3]}, [], [1 0.2], [1 1], [false false], ...
    [false false], [0 0], 'verbose', false);
results(end+1, :) = {'massMaet box on two attributes, and the share', ...
    closeM(massMaet(d, 'region', {1, [59 63.5]; 2, [-1 1.5]}), ...
    integral2(f2M(d), 59, 63.5, -1, 1.5, 'AbsTol', 1e-12), 1e-8) ...
    && closeM(massMaet(d, 'region', {1, [59 63.5]}, 'normalize', 'total'), ...
    massMaet(d, 'region', {1, [59 63.5]}) / 4, 1e-14)}; %#ok<SAGROW>

% ---- nested absolute ----------------------------------------------------------
pit = [60 62 64 65 67];
[pb, wb, sb] = unpackPreMaet(bindEvents({pit, 0:4}, [], [2 1], 'step', 1));
d = buildMaet(pb, wb, 'sigma', [0.5 0.2], 'isPer', [false false], ...
    'period', [0 0], 'specs', sb, 'verbose', false);
refN = 0;
ncdfM = @(z) 0.5 * erfc(-z / sqrt(2));
for n = 1:size(pb{1}, 2)
    a = pb{1}(1, n); b = pb{1}(2, n);
    refN = refN + (ncdfM((63 - a) / 0.5) - ncdfM((59 - a) / 0.5)) ...
                * (ncdfM((66 - b) / 0.5) - ncdfM((61 - b) / 0.5));
end
results(end+1, :) = {'massMaet box on a nested absolute attribute', ...
    closeM(massMaet(d, 'region', {1, [59 63; 61 66]}), refN, 1e-12 * refN) ...
    && closeM(massMaet(d), massMaet(d, 'region', {1, [-Inf Inf]}), 1e-13)}; %#ok<SAGROW>

% ---- inputs -------------------------------------------------------------------
pmM = packPreMaet(pM, wM, flatSpecs(pM, 'sigma', 1, 'isPer', false, 'period', 0));
dM = buildMaet(pmM, 'verbose', false);
mm = massMaet({dM, pmM}, 'region', {1, [61 66]});
results(end+1, :) = {'massMaet takes a pre-MAET and a cell', ...
    massMaet(pmM, 'region', {1, [61 66]}) == massMaet(dM, 'region', {1, [61 66]}) ...
    && isequal(size(mm), [1 2])}; %#ok<SAGROW>

% ---- refusals -----------------------------------------------------------------
refusedM = @(f, id) localRefused(f, id);
d3 = flatM(1, 3, true, false, 0);
warning('off', 'buildMaet:isRelDegenerate');
d1 = flatM(1, 1, true, false, 0);
warning('on', 'buildMaet:isRelDegenerate');
dp = flatM(1, 1, false, true, 12);
dc = buildMaet([0; 1; 2], ones(3, 1), 0.25 * eye(3), 3, false, false, 0, false, ...
    'verbose', false);
results(end+1, :) = {'massMaet refusals', ...
    refusedM(@() massMaet(d3, 'region', {1, [0 5]}), 'massMaet:noClosedForm') ...
    && refusedM(@() massMaet(d1, 'region', {1, [0 5]}), 'massMaet:noCoordinates') ...
    && refusedM(@() massMaet(dp, 'region', {1, [0 13]}), 'massMaet:badRegion') ...
    && refusedM(@() massMaet(dp, 'region', {1, [5 1]}), 'massMaet:badRegion') ...
    && refusedM(@() massMaet(dp, 'normalize', 'pdf'), 'massMaet:badNormalize') ...
    && refusedM(@() massMaet(dc, 'region', {1, [0 1]}), 'massMaet:kernelCov')}; %#ok<SAGROW>

% ---- sweptMass ----------------------------------------------------------------
pitS = [60 62 64 65 67 65 64 62 60 67 72 67];
onS = 0:11;
pmS = packPreMaet({pitS, onS}, [], flatSpecs({pitS, onS}, 'sigma', [0.5 0.1], ...
    'isPer', [false false], 'period', [0 0]));
valsS = 0:2:10;
gotS = sweptMass(pmS, 'sweep', {2, valsS}, 'window', {2, {'rect', 4}}, ...
    'drop', 2, 'region', {1, [63.5 67.5]});
shareS = sweptMass(pmS, 'sweep', {2, valsS}, 'window', {2, {'rect', 4}}, ...
    'drop', 2, 'region', {1, [63.5 67.5]}, 'normalize', 'total');
okS = true;
for i = 1:numel(valsS)
    [pw, ww] = unpackPreMaet(weightEvents(pmS, 2, 1, valsS(i), 1, ...
        'width', 4, 'dropInputAttr', true));
    dS = buildMaet(pw, ww, 0.5, 1, false, false, 0, 'verbose', false);
    okS = okS && closeM(gotS(i), massMaet(dS, 'region', {1, [63.5 67.5]}), 1e-12) ...
        && closeM(shareS(i), massMaet(dS, 'region', {1, [63.5 67.5]}, ...
        'normalize', 'total'), 1e-12);
end
results(end+1, :) = {'sweptMass matches weightEvents -> buildMaet -> massMaet', okS}; %#ok<SAGROW>
results(end+1, :) = {'sweptMass without a region counts the window', ...
    all(abs(sweptMass(pmS, 'sweep', {2, [2 5]}, 'window', {2, {'rect', 4}}, ...
    'drop', 2) - 4) < 1e-12)}; %#ok<SAGROW>
results(end+1, :) = {'sweptMass refuses a region on a dropped attribute', ...
    refusedM(@() sweptMass(pmS, 'sweep', {2, 2}, 'window', {2, {'rect', 4}}, ...
    'drop', 2, 'region', {2, [0 3]}), 'sweptMass:regionDropped')}; %#ok<SAGROW>

% ---- values shared with Python -------------------------------------------------
results(end+1, :) = {'massMaet cross-language values (1e-12)', ...
    closeM(massMaet(flatM(1, 2, true, false, 0), 'region', {1, [2 5]}), ...
        1.1795017491767164, 1e-12) ...
    && closeM(massMaet(flatM(2.5, 1, false, true, 12), 'region', {1, [10 17]}), ...
        1.7491633889274478, 1e-12) ...
    && closeM(massMaet(flatM(2.5, 1, false, true, 12, 'wrap', 'single-image'), ...
        'region', {1, [10 17]}), 1.7385705553936834, 1e-12) ...
    && closeM(massMaet(flatM(2.5, 1, false, true, 12), ...
        'region', {1, {'gaussian', 1, 2}}), 1.2307207984885715, 1e-12)}; %#ok<SAGROW>

warning('on', 'buildMaet:absPerSingleImage');
mptDefaults(prevHints);

if standalone
    nPass = sum([results{:, 2}]);
    fprintf('test_massMaet: %d/%d passed\n', nPass, size(results, 1));
    for i = 1:size(results, 1)
        if ~results{i, 2}
            fprintf('  FAIL: %s\n', results{i, 1});
        end
    end
end

function tf = localRefused(f, id)
try
    f();
    tf = false;
catch err
    tf = strcmp(err.identifier, id);
end
end
