%% test_grid_attr_table.m — sampling an attribute table on a grid
%
%  The acceptance case is Analysis 1.1 of the JMM article, which samples
%  BWV 347 on a sixteenth-note grid: N = 272 events, held notes
%  replicating across the points they occupy, and no rests.
%
%  Mirror of Python tests/test_grid_attr_table.py. Grid positions and note
%  identifiers are 1-based here and 0-based there, each idiomatic.
%
%  Standalone-runnable; appends to `results` when called from test_mpt.m.

if ~exist('results', 'var')
    results = {};
    standalone = true;
else
    standalone = false;
end
ge_tol = 1e-12;

% Two notes far enough apart that the grid has empty points.
ge_gapped = table([0; 3], [0; 1.5], [1; 1], [0.5; 0.5], [60; 64], ...
                  [90; 90], categorical({'A'; 'A'}, {'A', 'B'}), ...
                  [1; 1], [1; 1], [false; true], ...
                  'VariableNames', {'onsetBeats', 'onsetSeconds', ...
                  'durationBeats', 'durationSeconds', 'pitch', ...
                  'velocity', 'part', 'voice', 'measure', 'fermata'});

% One note of four beats and one of one, so replication is visible.
ge_held = table([0; 0], [0; 0], [4; 1], [2; 0.5], [60; 67], [90; 90], ...
                categorical({'A'; 'B'}, {'A', 'B'}), [1; 1], [1; 1], ...
                [false; false], ...
                'VariableNames', {'onsetBeats', 'onsetSeconds', ...
                'durationBeats', 'durationSeconds', 'pitch', ...
                'velocity', 'part', 'voice', 'measure', 'fermata'});

% --- the acceptance case -------------------------------------------------
ge_demos = fullfile(fileparts(fileparts(mfilename('fullpath'))), 'demos', 'jmm');
ge_added = ~contains(path, ge_demos);
if ge_added; addpath(ge_demos); end
ge_notes = jmm.bwv347Notes();
ge_bwv = gridAttrTable(ge_notes, 0.25);
results(end+1, :) = {'grid: BWV 347 gives the manuscript grid (N = 272)', ...
    numel(unique(ge_bwv.gridIndex)) == 272 ...
    && height(ge_bwv) == 272 * 4 ...
    && ~any(isnan(ge_bwv.noteId))}; %#ok<*SAGROW>

% --- replication and occupancy ------------------------------------------
ge_g = gridAttrTable(ge_held, 1);
ge_long  = ge_g(ge_g.noteId == 1, :);
ge_short = ge_g(ge_g.noteId == 2, :);
results(end+1, :) = {'grid: a held note replicates across the points it covers', ...
    height(ge_long) == 4 && height(ge_short) == 1 ...
    && isequal(ge_long.gridIndex(:).', 1:4)};

% Occupancy is half-open, so the note's end is the next note's point.
results(end+1, :) = {'grid: a note ending on a grid point does not occupy it', ...
    ~ismember(2, ge_short.gridIndex)};

results(end+1, :) = {'grid: duration still means the note''s own duration', ...
    all(ge_long.durationBeats == 4)};

% --- empty grid points ---------------------------------------------------
ge_gap = gridAttrTable(ge_gapped, 1);
ge_empty = ge_gap(isnan(ge_gap.noteId), :);
results(end+1, :) = {'grid: an empty point is a row with its note columns missing', ...
    height(ge_empty) == 2 && isequal(ge_empty.gridIndex(:).', [2 3]) ...
    && isequal(ge_empty.gridOnsetBeats(:).', [1 2]) ...
    && all(isnan(ge_empty.pitch)) && all(isnan(ge_empty.velocity)) ...
    && all(isnan(ge_empty.measure)) && all(isnan(ge_empty.fermata)) ...
    && all(isundefined(ge_empty.part))};

[ge_p, ge_w] = unpackPreMaet(preMaetFromAttrTable(ge_gap, ...
    'attributes', { ...
        struct('column', 'pitch', 'sigma', 1, 'r', 1, 'exch', true)}, ...
        'weights', 'weight', 'time', 'beats'));
results(end+1, :) = {'grid: empty points survive into a pre-MAET as events with no value', ...
    all(isnan(ge_p{1}(1, [2 3]))) && all(ge_w{1}(1, [2 3]) == 0)};

% --- weight policies -----------------------------------------------------
ge_item = gridAttrTable(ge_notes, 0.25, 'weights', 'item');
results(end+1, :) = {'grid: item weighting makes each note count once', ...
    abs(sum(ge_item.weight) - height(ge_notes)) < 1e-9};

% One note of a beat and a half, so it fills one slice and half of the
% next, and the three policies disagree.
ge_straddle = table(0, 0, 1.5, 0.75, 60, 90, categorical({'A'}, {'A'}), ...
                    1, 1, false, ...
                    'VariableNames', {'onsetBeats', 'onsetSeconds', ...
                    'durationBeats', 'durationSeconds', 'pitch', ...
                    'velocity', 'part', 'voice', 'measure', 'fermata'});
ge_pol = @(w) gridAttrTable(ge_straddle, 1, 'weights', w).weight(:).';
results(end+1, :) = {'grid: the three policies on a straddling note', ...
    max(abs(ge_pol('presence') - [1 1])) < ge_tol ...
    && max(abs(ge_pol('coverage') - [1 0.5])) < ge_tol ...
    && max(abs(ge_pol('item') - [2/3 1/3])) < 1e-12};

results(end+1, :) = {'grid: coverage is the default', ...
    max(abs(gridAttrTable(ge_straddle, 1).weight(:).' - [1 0.5])) < ge_tol};

results(end+1, :) = {'grid: presence counts a note once per slice it sounds in', ...
    abs(sum(gridAttrTable(ge_held, 1, 'weights', 'presence').weight) - 5) < ge_tol};

% A note falling between two grid points still overlaps a slice, so
% nothing disappears for being short.
ge_short = ge_straddle;
ge_short.onsetBeats = 0.25;
ge_short.durationBeats = 0.25;
ge_shortW = @(w) gridAttrTable(ge_short, 1, 'weights', w, 'limits', [0 1]).weight;
results(end+1, :) = {'grid: a note shorter than the step is not lost', ...
    abs(ge_shortW('presence') - 1) < ge_tol ...
    && abs(ge_shortW('coverage') - 0.25) < ge_tol ...
    && abs(ge_shortW('item') - 1) < ge_tol};

% The kernel is linear in weight, so splitting a note's weight over the
% points it covers leaves the density unchanged.
ge_density = @(pm) buildMaet(pm.pAttr, pm.wAttr, 50, 1, false, false, 0, ...
                             'verbose', false);
ge_un = ge_density(preMaetFromAttrTable(ge_notes, 'attributes', { ...
    struct('column', 'pitch', 'sigma', 1, 'r', 1, 'exch', true)}, ...
    'chords', 'separate', 'weights', 'ones', 'time', 'beats'));
ge_gr = ge_density(preMaetFromAttrTable(ge_item, 'attributes', { ...
    struct('column', 'pitch', 'sigma', 1, 'r', 1, 'exch', true)}, ...
    'weights', 'weight', 'time', 'beats'));
ge_qv = evalMaet(ge_un, {64}, 'verbose', false);
results(end+1, :) = {'grid: item weighting reproduces the ungridded density at r = 1', ...
    abs(evalMaet(ge_gr, {64}, 'verbose', false) - ge_qv) < 1e-9 * abs(ge_qv)};

% --- the grid specification ---------------------------------------------
results(end+1, :) = {'grid: it runs from zero to the last note''s end by default', ...
    abs(max(ge_gap.gridOnsetBeats) - 3) < ge_tol};

ge_lim = gridAttrTable(ge_gapped, 1, 'limits', [0 2]);
results(end+1, :) = {'grid: limits override the extent', ...
    numel(unique(ge_lim.gridIndex)) == 2};

ge_secs = gridAttrTable(ge_gapped, 0.5, 'time', 'seconds');
results(end+1, :) = {'grid: a seconds grid uses the seconds columns', ...
    any(strcmp(ge_secs.Properties.VariableNames, 'gridOnsetSeconds')) ...
    && numel(unique(ge_secs.gridIndex)) == 4};

ge_noSecs = removevars(ge_gapped, {'onsetSeconds', 'durationSeconds'});
results(end+1, :) = {'grid: gridding over a missing time base says so', ...
    errorMessageContains(@() gridAttrTable(ge_noSecs, 1, 'time', 'seconds'), ...
                         'beat map')};

% The grid steps in one unit; its points have a time in both, so a
% metrical grid can be read on a clock. Where the source carries one time
% base there is nothing to map the points onto.
results(end+1, :) = {'grid: the grid carries both time bases', ...
    any(strcmp(ge_secs.Properties.VariableNames, 'gridOnsetBeats')) ...
    && any(strcmp(ge_gap.Properties.VariableNames, 'gridOnsetSeconds'))};

ge_oneBase = gridAttrTable(ge_noSecs, 1);
results(end+1, :) = {'grid: one time base gives one grid onset', ...
    any(strcmp(ge_oneBase.Properties.VariableNames, 'gridOnsetBeats')) ...
    && ~any(strcmp(ge_oneBase.Properties.VariableNames, 'gridOnsetSeconds'))};

ge_sounding = ge_gapped;
ge_sounding.soundingDurationBeats = [3; 1];
results(end+1, :) = {'grid: the sounding duration may define occupancy', ...
    ~any(isnan(gridAttrTable(ge_sounding, 1, 'duration', 'soundingDuration').noteId))};

results(end+1, :) = {'grid: the step must be positive and finite', ...
    throwsErrorWithId(@() gridAttrTable(ge_gapped, 0), 'gridAttrTable:step') ...
    && throwsErrorWithId(@() gridAttrTable(ge_gapped, -1), 'gridAttrTable:step') ...
    && throwsErrorWithId(@() gridAttrTable(ge_gapped, Inf), 'gridAttrTable:step')};

ge_meta = ge_gap.Properties.UserData;
results(end+1, :) = {'grid: the result records that it is gridded', ...
    strcmp(ge_meta.granularity, 'grid') && ge_meta.gridStep == 1 ...
    && strcmp(ge_meta.gridTime, 'beats')};

if ge_added; rmpath(ge_demos); end

% --- the collapse back ---------------------------------------------------
% ungridAttrTable is the inverse: noteId says which row of the source
% each grid row came from. Notes outside an explicit 'limits' span are
% cut, which is a truncation the caller asked for rather than a failure
% of the collapse.
ge_full = gridAttrTable(ge_gapped, 1);
ge_back = ungridAttrTable(ge_full);
results(end+1, :) = {'grid: the grid collapses back to the table it came from', ...
    height(ge_back) == height(ge_gapped) ...
    && isequal(ge_back.Properties.VariableNames, ...
               ge_gapped.Properties.VariableNames) ...
    && isequaln(ge_back.pitch, ge_gapped.pitch) ...
    && isequaln(ge_back.onsetBeats, ge_gapped.onsetBeats)};

ge_cut = gridAttrTable(ge_gapped, 1, 'limits', [0 2]);
results(end+1, :) = {'grid: limits are the one lossy case', ...
    numel(unique(ge_cut.noteId(~isnan(ge_cut.noteId)))) < height(ge_gapped)};

% The grid adds weight to a table that had none and overwrites the weight
% of one that did, so the column it leaves is the slice's and not the
% note's. Comparing the two tables' columns would keep it;
% ungridAttrTable removes it and says so.
ge_weighted = ge_gapped;
ge_weighted.weight = [0.25; 0.75];
ge_unw = ungridAttrTable(gridAttrTable(ge_weighted, 1));
results(end+1, :) = {'grid: ungridding drops a weight the grid overwrote', ...
    ~any(strcmp(ge_unw.Properties.VariableNames, 'weight')) ...
    && isequaln(ge_unw.pitch, ge_weighted.pitch)};

results(end+1, :) = {'grid: ungridding needs a gridded table', ...
    throwsErrorWithId(@() ungridAttrTable(ge_gapped), ...
                      'ungridAttrTable:notGridded')};

% Rows and columns may go: the empty slices, a span of slices, or a
% column. A note whose first slice was dropped comes back from its next,
% the source's columns repeating unchanged across its slices.
ge_held = gridAttrTable(ge_gapped, 1);
ge_noEmpty = ge_held(~isnan(ge_held.noteId), :);
results(end+1, :) = {'grid: ungridding survives edits that keep it a grid', ...
    height(ungridAttrTable(ge_noEmpty)) == height(ge_gapped) ...
    && ~any(strcmp(ungridAttrTable(removevars(ge_held, 'velocity')) ...
                   .Properties.VariableNames, 'velocity'))};

% A per-slice quantity the caller added has no single value to collapse
% to, so the first slice's is taken and said so; one that is constant
% within a note is silent.
ge_w = warning('off', 'ungridAttrTable:variesWithinNote');
ge_restore = onCleanup(@() warning(ge_w));

% A note must span more than one slice for a per-slice column to vary
% within it, which at a step of 1 these one-beat notes do not.
ge_spanning = gridAttrTable(ge_gapped, 0.5);
ge_perSlice = ge_spanning;
ge_perSlice.perSlice = (1:height(ge_spanning)).';
lastwarn('');
ge_out = ungridAttrTable(ge_perSlice);
[~, ge_id] = lastwarn;
results(end+1, :) = {'grid: a column that varies within a note warns', ...
    strcmp(ge_id, 'ungridAttrTable:variesWithinNote') ...
    && any(strcmp(ge_out.Properties.VariableNames, 'perSlice'))};

ge_perNote = ge_held;
ge_perNote.tag = 2 * ge_held.pitch;
lastwarn('');
ge_out = ungridAttrTable(ge_perNote);
[~, ge_id] = lastwarn;
results(end+1, :) = {'grid: a column constant within a note is silent', ...
    isempty(ge_id) && isequaln(ge_out.tag, 2 * ge_gapped.pitch)};
clear ge_restore

% --- regridding ----------------------------------------------------------
% Gridding the grid equals gridding the notes. Each policy combines in the
% way that makes this hold: coverage sums and rescales by fine / coarse,
% item sums, presence takes the maximum.
ge_pairs = [0.25 1; 0.25 0.5; 0.5 1; 0.25 2; 0.25 0.25];
ge_policies = {'coverage', 'presence', 'item'};
ge_ok = true;
for ge_p = 1:numel(ge_policies)
    for ge_k = 1:size(ge_pairs, 1)
        ge_fine = ge_pairs(ge_k, 1); ge_coarse = ge_pairs(ge_k, 2);
        ge_direct = gridAttrTable(ge_notes, ge_coarse, ...
            'weights', ge_policies{ge_p}, 'limits', [0 68]);
        ge_regrid = gridAttrTable(gridAttrTable(ge_notes, ge_fine, ...
            'weights', ge_policies{ge_p}, 'limits', [0 68]), ge_coarse, ...
            'weights', ge_policies{ge_p});
        ge_ok = ge_ok && height(ge_regrid) == height(ge_direct) ...
            && isequal(ge_regrid.Properties.VariableNames, ...
                       ge_direct.Properties.VariableNames) ...
            && isequaln(ge_regrid.gridIndex, ge_direct.gridIndex) ...
            && isequaln(ge_regrid.noteId, ge_direct.noteId) ...
            && isequaln(ge_regrid.pitch, ge_direct.pitch) ...
            && max(abs(ge_regrid.weight - ge_direct.weight)) < ge_tol ...
            && max(abs(ge_regrid.gridOnsetBeats - ...
                       ge_direct.gridOnsetBeats)) < ge_tol ...
            && max(abs(ge_regrid.gridOnsetSeconds - ...
                       ge_direct.gridOnsetSeconds)) < ge_tol;
    end
end
results(end+1, :) = {'grid: gridding the grid equals gridding the notes', ge_ok};

% A coarse slice holding no note keeps its place, as it does when the
% notes are gridded directly.
ge_ferm = ge_notes(ge_notes.fermata, :);
ge_direct = gridAttrTable(ge_ferm, 1, 'limits', [0 68]);
ge_regrid = gridAttrTable(gridAttrTable(ge_ferm, 0.25, 'limits', [0 68]), 1);
results(end+1, :) = {'grid: regridding keeps the empty slices', ...
    height(ge_regrid) == height(ge_direct) ...
    && sum(isnan(ge_regrid.noteId)) == sum(isnan(ge_direct.noteId)) ...
    && sum(isnan(ge_direct.noteId)) > 0 ...
    && isequaln(ge_regrid.noteId, ge_direct.noteId)};

% The point of regridding: weight the fine slices as the analysis requires
% and the weights carry through the coarsening. Weighting the two eighths
% of a beat 1 and 1/2, normalized to mean one, is the metrical weighting of
% Analysis 1.4 of the JMM article; a note sounding through the beat then
% weighs 1 and one sounding only its second half weighs 1/3.
ge_e8 = gridAttrTable(ge_notes, 0.5, 'limits', [0 68]);
ge_onBeat = abs(mod(ge_e8.gridOnsetBeats, 1)) < 1e-9;
ge_metric = 0.5 * ones(height(ge_e8), 1);
ge_metric(ge_onBeat) = 1;
ge_e8.weight = ge_e8.weight .* ge_metric / 0.75;
ge_beats = gridAttrTable(ge_e8, 1);
ge_first = sort(ge_beats.weight(ge_beats.gridIndex == 1));
results(end+1, :) = {'grid: regridding carries a weighting of the fine slices', ...
    numel(ge_first) == 5 ...
    && max(abs(ge_first - [1/3; 2/3; 1; 1; 1])) < 1e-12};

% What it refuses.
ge_g = gridAttrTable(ge_notes, 0.5, 'limits', [0 68]);
ge_ids = cell(1, 5);
ge_calls = {@() gridAttrTable(ge_g, 0.75), ...
            @() gridAttrTable(ge_g, 0.25), ...
            @() gridAttrTable(ge_g, 1, 'weights', 'item'), ...
            @() gridAttrTable(ge_g, 1, 'limits', [0 4]), ...
            @() gridAttrTable(ge_g, 1, 'time', 'seconds')};
for ge_k = 1:5
    try
        ge_calls{ge_k}();
        ge_ids{ge_k} = '';
    catch ge_err
        ge_ids{ge_k} = ge_err.identifier;
    end
end
results(end+1, :) = {'grid: regridding refuses what it cannot align', ...
    isequal(ge_ids, {'gridAttrTable:regridStep', ...
                     'gridAttrTable:regridFiner', ...
                     'gridAttrTable:regridWeights', ...
                     'gridAttrTable:regridLimits', ...
                     'gridAttrTable:regridTime'})};

% The policy is recorded so that a regrid knows how the weights combine;
% ungridding removes it with the rest of the grid.
results(end+1, :) = {'grid: ungridding forgets the weighting policy', ...
    strcmp(ge_g.Properties.UserData.gridWeights, 'coverage') ...
    && ~isfield(ungridAttrTable(ge_g).Properties.UserData, 'gridWeights')};

if standalone
    nPass = sum([results{:, 2}]);
    fprintf('\n=== test_grid_attr_table: %d passed, %d failed (of %d) ===\n', ...
            nPass, size(results, 1) - nPass, size(results, 1));
end
