function tables = enumerateContingencyTables(rowSums, colSums)
%MOBIUS.ENUMERATECONTINGENCYTABLES  All non-negative integer matrices
%   with the given row and column margins.
%
%   TABLES = MOBIUS.ENUMERATECONTINGENCYTABLES(ROWSUMS, COLSUMS) returns
%   a cell array of qA-by-qB integer matrices, one per non-negative
%   integer matrix whose row sums equal ROWSUMS and column sums equal
%   COLSUMS, where qA = numel(ROWSUMS) and qB = numel(COLSUMS).
%
%   Returns {} if sum(ROWSUMS) ~= sum(COLSUMS) (no valid matrix exists).
%
%   The order of yield is the natural lexicographic order generated by
%   filling rows top-to-bottom and entries left-to-right; each cell
%   entry is a fresh matrix.
%
%   Example:
%     T = mobius.enumerateContingencyTables([1 1], [1 1]);
%     %   {[1 0; 0 1], [0 1; 1 0]}
%
%   See also MOBIUS.CANONICALFORM, MOBIUS.LABELLEDPAIRSREALISINGM.

    arguments
        rowSums (1,:) {mustBeInteger, mustBeNonnegative}
        colSums (1,:) {mustBeInteger, mustBeNonnegative}
    end

    if sum(rowSums) ~= sum(colSums)
        tables = {};
        return
    end

    qA = numel(rowSums);
    qB = numel(colSums);

    tables = {};
    M = zeros(qA, qB);
    helper(M, 1, 1, rowSums, colSums);

    function helper(Mloc, i, j, remRows, remCols)
        if i > qA
            tables{end+1} = Mloc;
            return
        end
        if j == qB
            % Last column on row i: forced to absorb the row's residual.
            v = remRows(i);
            if v <= remCols(j)
                Mloc(i, j) = v;
                newCols = remCols;
                newCols(j) = newCols(j) - v;
                helper(Mloc, i + 1, 1, remRows, newCols);
            end
        else
            maxV = min(remRows(i), remCols(j));
            for v = 0:maxV
                Mloc(i, j) = v;
                newRows = remRows;
                newRows(i) = newRows(i) - v;
                newCols = remCols;
                newCols(j) = newCols(j) - v;
                helper(Mloc, i, j + 1, newRows, newCols);
            end
        end
    end
end
