function checkAnisoConstraints(r, K, isRel, isPer, isSym, nestedAttr, name)
%CHECKANISOCONSTRAINTS  Enforce the mode constraints for matrix sigma.
%
%   internal.checkAnisoConstraints(R, K, ISREL, ISPER, ISSYM,
%   NESTEDATTR, NAME) errors unless the attribute is ordered
%   (isSym = false), absolute (isRel = false), non-periodic
%   (isPer = false), non-nested, and its tuple is its whole multiset
%   (r == K).

    if nargin < 7, name = 'sigma'; end
    if nestedAttr
        error('mpt:aniso:nested', ...
            ['%s: a matrix-valued kernel covariance is not supported ' ...
             'on nested attributes.'], name);
    end
    if logical(isSym)
        error('mpt:aniso:symmetric', ...
            ['%s: a matrix-valued kernel covariance requires an ' ...
             'ordered multiset (isSym = false); the symmetric power ' ...
             'requires a permutation-invariant kernel.'], name);
    end
    if logical(isRel)
        error('mpt:aniso:relative', ...
            ['%s: a matrix-valued kernel covariance requires ' ...
             'isRel = false; exact common-shift invariance remains ' ...
             'the province of isRel = true, and graded shift ' ...
             'tolerance is expressed within the covariance (an ' ...
             'sdShift^2 * ones ridge; see intervalKernelCov).'], name);
    end
    if logical(isPer)
        error('mpt:aniso:periodic', ...
            ['%s: a matrix-valued kernel covariance requires ' ...
             'isPer = false; periodic wrapping does not commute with ' ...
             'the anisotropic change of coordinates.'], name);
    end
    if round(r) ~= round(K)
        error('mpt:aniso:rNotK', ...
            ['%s: a matrix-valued kernel covariance requires the ' ...
             'attribute''s tuple to be its whole multiset (r == K); ' ...
             'got r = %d, K = %d. The covariance is that of the ' ...
             'complete ordered tuple.'], name, round(r), round(K));
    end
end
