function v = preMaetParseCov(text)
%PREMAETPARSECOV  'cov(sdPosition=..., ...)' -> [pos int shift], or [].
%
%   A covariance is a matrix, but the covariance an analysis wants is
%   generated by three scalars (Milne 2026, Sec. maet-cov): with D the
%   difference operator,
%
%       Sigma = sdPosition^2 D D' + sdInterval^2 I + sdShift^2 J
%
%   so intervalKernelCov rebuilds it from numbers a spreadsheet can hold.
%   Omitted terms are zero. The row's own r gives the order.
text = strtrim(text);
v = [];
if numel(text) < 5 || ~strncmpi(text, 'cov(', 4) || text(end) ~= ')'
    return;
end
keys = {'sdposition', 'sdinterval', 'sdshift'};
v = zeros(1, 3);
items = internal.preMaetSplitTop(text(5:end-1));
found = false;
for k = 1:numel(items)
    item = strtrim(items{k});
    if isempty(item); continue; end
    eq = strfind(item, '=');
    if isempty(eq)
        error('readPreMaet:cov', ...
            'Covariance parameters must be name=value, got ''%s''.', item);
    end
    key = lower(strtrim(item(1:eq(1)-1)));
    key = strrep(strrep(key, '_', ''), ' ', '');
    idx = find(strcmp(key, keys), 1);
    if isempty(idx)
        error('readPreMaet:covKey', ...
            ['Unknown covariance parameter ''%s''; expected ' ...
             'sdPosition, sdInterval, sdShift.'], key);
    end
    v(idx) = str2double(item(eq(1)+1:end));
    found = true;
end
if ~found
    error('readPreMaet:covEmpty', ...
        '''%s'' names no covariance parameters.', text);
end
end
