function v = preMaetParseCov(text)
%PREMAETPARSECOV  'cov(differenced=..., sdValue=..., ...)' ->
%[differenced pos int shift], or [].
%
%   A covariance is a matrix, but the covariance an analysis wants is
%   generated by three widths and a choice of case (Milne 2026, Sec.
%   maet-cov): with D the difference operator, S the cumulative-sum
%   map, P the centring projector, and J the all-ones matrix,
%
%       differenced = 0:  Sigma = sdValue^2 I + sdInterval^2 P S S' P
%                                 + sdShift^2 J
%       differenced = 1:  Sigma = sdValue^2 D D' + sdInterval^2 I
%                                 + sdShift^2 J
%
%   so kernelCov rebuilds it from numbers a spreadsheet can hold.
%   Omitted widths are zero; the flag is required. The row's own r
%   gives the order.
text = strtrim(text);
v = [];
if numel(text) < 5 || ~strncmpi(text, 'cov(', 4) || text(end) ~= ')'
    return;
end
keys = {'differenced', 'sdvalue', 'sdinterval', 'sdshift'};
v = zeros(1, 4);
items = internal.preMaetSplitTop(text(5:end-1));
found = false;
flagSeen = false;
for k = 1:numel(items)
    item = strtrim(items{k});
    if isempty(item); continue; end
    eq = strfind(item, '=');
    if isempty(eq)
        error('readPreMaet:cov', ...
            'Covariance parameters must be name=value, got ''%s''.', item);
    end
    key = lower(strtrim(item(1:eq(1)-1)));
    key = strrep(strrep(key, '_', ''), ' ', '');
    idx = find(strcmp(key, keys), 1);
    if isempty(idx)
        error('readPreMaet:covKey', ...
            ['Unknown covariance parameter ''%s''; expected ' ...
             'differenced, sdValue, sdInterval, sdShift.'], key);
    end
    val = lower(strtrim(item(eq(1)+1:end)));
    if idx == 1
        if any(strcmp(val, {'1', 'true'}))
            v(1) = 1;
        elseif any(strcmp(val, {'0', 'false'}))
            v(1) = 0;
        else
            error('readPreMaet:covFlag', ...
                'differenced must be 0/1 or false/true in ''%s''.', text);
        end
        flagSeen = true;
    else
        v(idx) = str2double(val);
        found = true;
    end
end
if ~found
    error('readPreMaet:covEmpty', ...
        '''%s'' names no covariance parameters.', text);
end
if ~flagSeen
    error('readPreMaet:covNoFlag', ...
        ['''%s'' does not say whether the tuple is differenced: a ' ...
         'cov(...) cell must carry differenced=0 (values) or ' ...
         'differenced=1 (first differences).'], text);
end
end
