function [Sigma, R] = validateKernelCov(Sigma, dim, name)
%VALIDATEKERNELCOV  Validate a kernel covariance; return (Sigma, R).
%
%   [SIGMA, R] = internal.validateKernelCov(SIGMA, DIM, NAME) returns
%   SIGMA as double and R, its lower-triangular Cholesky factor
%   (SIGMA = R * R'). Errors on a non-square, wrongly sized,
%   asymmetric, non-finite, or non-positive-definite input (a failed
%   Cholesky factorization is the definiteness test, consistent with
%   the toolbox rule that PSD validation always errors rather than
%   repairing). DIM may be [] to skip the size check.

    if nargin < 3, name = 'sigma'; end
    Sigma = double(Sigma);
    if ~ismatrix(Sigma) || size(Sigma, 1) ~= size(Sigma, 2)
        error('mpt:aniso:notSquare', ...
            ['%s: a matrix-valued kernel covariance must be square; ' ...
             'got shape %dx%d.'], name, size(Sigma, 1), size(Sigma, 2));
    end
    if ~isempty(dim) && size(Sigma, 1) ~= dim
        error('mpt:aniso:wrongSize', ...
            ['%s: kernel covariance is %dx%d but the attribute''s ' ...
             'tuple dimension is %d; the covariance must be r x r ' ...
             'with r the tuple size.'], ...
            name, size(Sigma, 1), size(Sigma, 2), dim);
    end
    if ~all(isfinite(Sigma(:)))
        error('mpt:aniso:notFinite', ...
            ['%s: kernel covariance must be finite. For exact ' ...
             'common-shift (transposition/tempo) invariance use ' ...
             'isRel = true rather than an infinite shift variance.'], ...
            name);
    end
    if max(abs(Sigma - Sigma.'), [], 'all') > 1e-12 * max(abs(Sigma(:)))
        error('mpt:aniso:notSymmetric', ...
            '%s: kernel covariance must be symmetric.', name);
    end
    % Definiteness test: one attempted Cholesky factorization.
    [R, flag] = chol(Sigma, 'lower');
    if flag ~= 0
        error('mpt:aniso:notPositiveDefinite', ...
            ['%s: kernel covariance must be positive definite ' ...
             '(Cholesky factorization failed). A singular covariance ' ...
             'means infinite tolerance along a null direction, which ' ...
             'a finite Gaussian kernel cannot represent; for the ' ...
             'exact common-shift quotient use isRel = true.'], name);
    end
end
