function warnAbsPerSingleImage(sigmaOverP)
%WARNABSPERSINGLEIMAGE  Warn that abs-per was opted into single-image at high sigma/P.
%
%   INTERNAL.WARNABSPERSINGLEIMAGE(SIGMAOVERP) emits the toolbox-wide
%   warning that an absolute-periodic attribute has been opted into the
%   single-image (minimum-image) measure at a sigma/period where that
%   departs from the full-image measure (the toolbox default).
%
%   Raised at density construction rather than at any one operation,
%   because the choice is a property of the density: evaluation, inner
%   product, and entropy all inherit it.
%
%   Fires only when the user has explicitly passed
%   ``wrap = 'single-image'`` on this attribute. The default full-image
%   measure is positive definite by construction; the warning is silent
%   in the ordinary case. The two measures agree below the threshold,
%   so the warning is also silent in the range musical work normally
%   occupies.
%
%   Above roughly sigma/period = 0.15 the single-image kernel is no
%   longer positive definite, so a cosine computed from it is not
%   constrained to [-1, 1] and can exceed 1.
%
%   Mirror of Python dispatch._warn_abs_per_single_image.
    warning('buildExpTens:absPerSingleImage', ...
        ['sigma/period = %.3f exceeds 0.05: this absolute-periodic ' ...
         'attribute has been opted into the single-image (minimum-image) ' ...
         'measure, which above this sigma/period departs from the ' ...
         'full-image measure that sums the kernel over every periodic ' ...
         'image (the two agree below it). Everything computed from ' ...
         'this density inherits the choice. Above roughly ' ...
         'sigma/period = 0.15 the single-image kernel also stops being ' ...
         'positive definite, so a cosine similarity computed from it ' ...
         'is not bounded by 1. Drop ``wrap = ''single-image''`` ' ...
         '(the toolbox default is the full-image measure) or reduce ' ...
         'sigma relative to the period if the measure matters at this ' ...
         'scale.'], sigmaOverP);
end
