"""premaet_io.py -- read and write a pre-MAET as CSV.

A pre-MAET is a table: one row per attribute, its parameters at the left
and one column per event (Milne 2026, Def. 2.6). That is also a
spreadsheet, so an analysis can be laid out in Excel or Numbers, exported
as CSV, and read straight in --- and any pre-MAET the toolbox holds can be
written back out the same way.

The cells use the notation of the article and of
:func:`~mpt.show_pre_maet`: braces for an unordered multiset, parentheses
for an ordered one, brackets within brackets for a nested attribute, and
``60^(0.6)`` for a weighted value. The writer and the reader are
therefore inverse, and a pre-MAET survives a round trip through a
spreadsheet unchanged.

The header is fixed: ``name, sigma, r, rel, per, P, sym`` followed by one
column per event, whose own headings are free text (``n = 1``, a bar
number, a label). ``r``, ``rel`` and ``sym`` take a parenthesised tuple on
a nested attribute, innermost level first, exactly as the article writes
them. An empty parameter cell is absent; ``NA`` is NA.
"""
from __future__ import annotations

import csv
import io

import numpy as np

from .premaet import pre_maet, shift_lead

PARAM_COLUMNS = ("name", "sigma", "r", "rel", "per", "P", "sym")

_OPEN = {"{": True, "(": False}      # bracket -> is the level unordered?
_CLOSE = {"{": "}", "(": ")"}


# -------------------------------------------------------------------
#  Cell grammar
# -------------------------------------------------------------------

def _split_top(text):
    """Split on commas that are not inside a bracket."""
    out, depth, cur = [], 0, ""
    for ch in text:
        if ch in "{(":
            depth += 1
        elif ch in "})":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip() != "" or out:
        out.append(cur)
    return [t.strip() for t in out]


def _parse_cell(text):
    """Parse one cell into ``(node, sym_levels)``.

    ``node`` is a nested list of ``(value, weight)`` leaves, outermost
    grouping first; ``sym_levels`` runs innermost first, as in a spec.
    """
    text = text.strip()
    if text == "":
        return [], []
    if text[0] not in _OPEN:
        return [_parse_leaf(text)], []
    sym = _OPEN[text[0]]
    if text[-1] != _CLOSE[text[0]]:
        raise ValueError(f"Unbalanced brackets in cell {text!r}.")
    inner = text[1:-1].strip()
    if inner == "":
        return [], [sym]
    parts = _split_top(inner)
    if any(p[:1] in _OPEN for p in parts):
        children, below = [], None
        for part in parts:
            node, lv = _parse_cell(part)
            children.append(node)
            below = lv if below is None else below
        return children, (below or []) + [sym]
    return [_parse_leaf(p) for p in parts], [sym]


def _parse_leaf(text):
    """``60`` or ``60^(0.6)`` -> ``(value, weight or None)``."""
    text = text.strip()
    if "^" not in text:
        return float(text), None
    val, _, wt = text.partition("^")
    wt = wt.strip()
    if wt.startswith("(") and wt.endswith(")"):
        wt = wt[1:-1]
    return float(val), float(wt)


def _flatten(node, depth):
    """Leaves in reading order with their group path, for the tag matrix."""
    if depth == 0:
        return [((), leaf) for leaf in node]
    out = []
    for g, child in enumerate(node):
        for path, leaf in _flatten(child, depth - 1):
            out.append(((g,) + path, leaf))
    return out


def _depth(node):
    return 1 + _depth(node[0]) if node and isinstance(node[0], list) else 0


# -------------------------------------------------------------------
#  Kernel covariances in a cell
# -------------------------------------------------------------------
#
# A covariance is a matrix, but the covariance an analysis actually wants
# is generated by three scalars (Milne 2026, Sec. maet-cov): with D the
# difference operator,
#
#     Sigma = sd_position^2 D D' + sd_interval^2 I + sd_shift^2 J
#
# so ``interval_kernel_cov(r, ...)`` rebuilds it from numbers a spreadsheet
# can hold. The cell carries those three rather than the matrix, written
# ``cov(sd_position=0.2, sd_interval=0.3, sd_shift=0.5)``; omitted terms
# are zero. The row's own ``r`` gives the order.

_COV_KEYS = ("sd_position", "sd_interval", "sd_shift")


def _parse_cov(text):
    """``cov(sd_position=..., ...)`` -> a dict, or None if not a cov cell."""
    t = text.strip()
    if not t.lower().startswith("cov(") or not t.endswith(")"):
        return None
    out = {}
    for item in _split_top(t[4:-1]):
        if not item:
            continue
        key, _, val = item.partition("=")
        # Either spelling is read: a file may have been written by hand
        # in a spreadsheet, or by the MATLAB twin, and the parameter is
        # the same parameter under either convention.
        key = key.strip().lower().replace("_", "")
        key = {"sdposition": "sd_position", "sdinterval": "sd_interval",
               "sdshift": "sd_shift"}.get(key, key)
        if key not in _COV_KEYS:
            raise ValueError(
                f"Unknown covariance parameter {key!r} in {text!r}; "
                f"expected {', '.join(_COV_KEYS)}.")
        out[key] = float(val)
    if not out:
        raise ValueError(f"{text!r} names no covariance parameters.")
    return out


def _cov_from_params(params, r):
    from ..serial import interval_kernel_cov
    return interval_kernel_cov(int(r), **{k: params.get(k, 0.0)
                                          for k in _COV_KEYS})


def _cov_to_params(C):
    """The three generating scalars of a covariance, or None.

    Recovered from the structure rather than remembered: the diagonal is
    ``2a + b + c``, the first off-diagonal ``c - a``, and every entry
    further out ``c``, so a matrix of this family is determined by three
    of its entries and verified by rebuilding it. A covariance of any
    other shape returns None and cannot be written.
    """
    C = np.asarray(C, dtype=float)
    r = C.shape[0]
    if r < 3 or C.shape[0] != C.shape[1]:
        return None
    c = float(C[0, 2])
    a = c - float(C[0, 1])
    b = float(C[0, 0]) - 2.0 * a - c
    if min(a, b, c) < -1e-12:
        return None
    vals = {k: float(np.sqrt(max(v, 0.0)))
            for k, v in zip(_COV_KEYS, (a, b, c))}
    if not np.allclose(_cov_from_params(vals, r), C, atol=1e-9):
        return None
    return vals


# -------------------------------------------------------------------
#  Parameter cells
# -------------------------------------------------------------------

def _parse_param(text, cast=float):
    """A parameter cell: empty is absent, ``NA`` is NA, else a value or a
    parenthesised per-level tuple."""
    text = (text or "").strip()
    if text == "":
        return None
    if text.upper() == "NA":
        return float("nan")
    if text.startswith("(") and text.endswith(")"):
        return [cast(v) for v in _split_top(text[1:-1])]
    return cast(text)


def _fmt_param(v):
    if v is None:
        return ""
    arr = np.asarray(v, dtype=float)
    if arr.ndim >= 2:
        params = _cov_to_params(arr)
        if params is None:
            raise ValueError(
                "This kernel covariance cannot be written to CSV. The "
                "format carries a covariance as the three scalars that "
                "generate it (sd_position, sd_interval, sd_shift), and "
                "this matrix is not of that family --- so there are no "
                "such scalars to write. Set it on the spec after "
                "reading instead.")
        return ("cov(" + ", ".join(f"{k}={params[k]:g}"
                                   for k in _COV_KEYS) + ")")
    if arr.ndim == 0 or arr.size == 1:
        v = float(arr.reshape(-1)[0])
        return "NA" if np.isnan(v) else f"{v:g}"
    return "(" + ", ".join("NA" if np.isnan(x) else f"{x:g}"
                           for x in arr.ravel()) + ")"


# -------------------------------------------------------------------
#  Reader
# -------------------------------------------------------------------

def read_pre_maet(source, *, delimiter=","):
    """Read a pre-MAET from a CSV file, path, or string.

    Parameters
    ----------
    source : str or path or file-like
        A path, or the CSV text itself (anything containing a newline is
        treated as text), or an open file.
    delimiter : str, default ','
        Passed to :mod:`csv`; use ``'\\t'`` for a tab-separated export.

    Returns
    -------
    dict
        The pre-MAET. Its ``p_attr`` holds the per-attribute
        ``(K_a, N)`` value matrices, NaN-padded where events carry
        different numbers of elements; its ``w_attr`` the weight
        matrices, or ``None`` where no cell carried a weight; its
        ``specs`` the per-attribute specs carrying ``r``, ``rel``,
        ``sym``, ``name`` and, where the file gives them, ``sigma``,
        ``is_per`` and ``period``, a nested attribute also carrying its
        ``tags``.

    See Also
    --------
    write_pre_maet, show_pre_maet, build_exp_tens
    """
    rows = _rows(source, delimiter)
    if not rows:
        raise ValueError("The pre-MAET file is empty.")
    header = [h.strip() for h in rows[0]]
    lower = [h.lower() for h in header]
    for k, col in enumerate(PARAM_COLUMNS):
        if k >= len(lower) or lower[k] != col.lower():
            raise ValueError(
                f"The header must begin {', '.join(PARAM_COLUMNS)} "
                f"followed by one column per event; got "
                f"{', '.join(header[:len(PARAM_COLUMNS)])}.")
    n_par = len(PARAM_COLUMNS)
    body = [r for r in rows[1:] if any(str(c).strip() for c in r)]
    if not body:
        raise ValueError("The pre-MAET file has a header but no attributes.")
    N = max(len(r) for r in body) - n_par
    if N < 1:
        raise ValueError("The pre-MAET file has no event columns.")

    p_attr, w_attr, specs, any_w = [], [], [], False
    for a, row in enumerate(body):
        row = list(row) + [""] * (n_par + N - len(row))
        name = row[0].strip() or None
        cells = [_parse_cell(c) for c in row[n_par:n_par + N]]
        nodes = [c[0] for c in cells]
        sym_seen = next((c[1] for c in cells if c[1]), [])
        depth = max((_depth(nd) for nd in nodes), default=0)
        P, W, tags = _stack(nodes, depth, a, name)
        spec = {"name": name} if name else {}
        spec["r"] = _levels_or_scalar(_parse_param(row[2], int), depth)
        spec["rel"] = _levels_or_scalar(_parse_param(row[4 - 1], int), depth)
        sym_col = _parse_param(row[6], int)
        spec["sym"] = _levels_or_scalar(
            sym_col if sym_col is not None
            else ([int(v) for v in sym_seen] if sym_seen else 1), depth)
        if depth > 0:
            spec["tags"] = tags
        cov = _parse_cov(row[1])
        if cov is not None:
            r_a = spec["r"]
            spec["sigma"] = _cov_from_params(
                cov, r_a[-1] if isinstance(r_a, list) else r_a)
        else:
            sigma = _parse_param(row[1])
            if sigma is not None:
                spec["sigma"] = sigma
        per = _parse_param(row[4], int)
        if per is not None:
            spec["is_per"] = bool(per) if not _isnan(per) else float("nan")
        period = _parse_param(row[5])
        if period is not None:
            spec["period"] = period
        p_attr.append(P)
        w_attr.append(W)
        any_w = any_w or W is not None
        specs.append(spec)

    if any_w:
        w_out = [np.ones_like(p_attr[a]) if w_attr[a] is None else w_attr[a]
                 for a in range(len(p_attr))]
        for a in range(len(p_attr)):
            w_out[a] = np.where(np.isnan(p_attr[a]), np.nan, w_out[a])
    else:
        w_out = None
    return pre_maet(p_attr, w_out, specs)


def _isnan(v):
    try:
        return bool(np.isnan(float(v)))
    except (TypeError, ValueError):
        return False


def _levels_or_scalar(v, depth):
    """A per-level list for a nested attribute, a scalar for a flat one."""
    if v is None:
        return [1] * (depth + 1) if depth else 1
    if isinstance(v, list):
        return [int(x) for x in v]
    return int(v)


def _stack(nodes, depth, a, name):
    """Value, weight, and tag matrices for one attribute's cells.

    Events may carry different numbers of elements, and a nested
    attribute's groups may differ in size between events; both are
    NaN-padded to the widest, which is the toolbox's standard convention
    for variable cardinality.
    """
    flat = [_flatten(nd, depth) for nd in nodes]
    if depth == 0:
        K = max((len(f) for f in flat), default=0)
        slots = [((), i) for i in range(K)]
    else:
        # One slot per (group path, position), sized by the widest event.
        widest = {}
        for f in flat:
            counts = {}
            for path, _ in f:
                counts[path] = counts.get(path, 0) + 1
            for path, c in counts.items():
                widest[path] = max(widest.get(path, 0), c)
        slots = [(path, i) for path in sorted(widest)
                 for i in range(widest[path])]
    K = len(slots)
    N = len(nodes)
    P = np.full((K, N), np.nan)
    W = np.full((K, N), np.nan)
    saw_w = False
    for n, f in enumerate(flat):
        seen = {}
        for path, (val, wt) in f:
            i = seen.get(path, 0)
            seen[path] = i + 1
            try:
                k = slots.index((path, i))
            except ValueError:
                raise ValueError(
                    f"Attribute {name or a}: event {n + 1} has more "
                    f"elements in one group than any other event.") from None
            P[k, n] = val
            if wt is not None:
                W[k, n] = wt
                saw_w = True
    if depth == 0:
        tags = None
    else:
        tags = np.array([list(path) for path, _ in slots], dtype=np.intp)
    return P, (W if saw_w else None), tags


def _rows(source, delimiter):
    if hasattr(source, "read"):
        return list(csv.reader(source, delimiter=delimiter))
    text = str(source)
    if "\n" not in text and "\r" not in text:
        with open(text, newline="") as fh:
            return list(csv.reader(fh, delimiter=delimiter))
    return list(csv.reader(io.StringIO(text), delimiter=delimiter))


# -------------------------------------------------------------------
#  Writer
# -------------------------------------------------------------------

def _render_csv(names, sp, params, P, W, cols, decimals,
                headings, delimiter):
    """The pre-MAET as CSV, in the format :func:`read_pre_maet` reads.

    Called by :func:`~mpt.show_pre_maet` under ``format='csv'`` so that
    one renderer owns the cell grammar and the three renderings cannot
    drift apart.
    """
    from .show import _cell_tree, _render_node
    A = len(P)
    N = len(cols)
    if headings is None:
        headings = [f"n = {c + 1}" for c in cols]
    elif len(headings) != N:
        raise ValueError(f"headings must have length {N}.")

    out = io.StringIO()
    wr = csv.writer(out, delimiter=delimiter, lineterminator="\n")
    wr.writerow(list(PARAM_COLUMNS) + list(headings))
    for a in range(A):
        spec = sp[a]
        row = [names[a] or "",
               _fmt_param(params["sigma"][a]),
               _fmt_param(_levels(spec, "r", 1)),
               _fmt_param([int(v) for v in _levels(spec, "rel", 0)]),
               _fmt_param(_as_flag(params["is_per"][a])),
               _fmt_param(params["period"][a]),
               _fmt_param([int(v) for v in _levels(spec, "sym", 1)])]
        # A file records what the pre-MAET holds, so weights are decided
        # per attribute rather than for the table as a whole: an
        # attribute whose weights are all exactly 1 is written bare,
        # since unit weights are what a bare value means.
        show_w = False
        if W is not None:
            live = np.isfinite(P[a]) & np.isfinite(W[a])
            show_w = bool(live.any()) and not np.allclose(W[a][live], 1.0)
        for c in cols:
            node, sym_levels = _cell_tree(
                P[a][:, c], None if W is None else W[a][:, c], spec, None)
            row.append(_render_node(node, sym_levels, decimals,
                                    show_w, False))
        wr.writerow(row)
    return out.getvalue()


def write_pre_maet(destination, p_attr, w_attr=None, specs=None,
                   **kwargs):
    """Write a pre-MAET as CSV, in the format :func:`read_pre_maet` reads.

    The rendering is :func:`~mpt.show_pre_maet`'s under ``format='csv'``,
    so the cells carry the notation of the article and the file is what
    :func:`read_pre_maet` reads: a pre-MAET survives a round trip through
    a spreadsheet unchanged. Every ``show_pre_maet`` argument is accepted;
    a file carries the whole pre-MAET, so nothing is elided.

    ``destination`` is a path or an open file; pass ``None`` to get the
    CSV text back without writing it. The text is returned either way.

    See Also
    --------
    read_pre_maet, show_pre_maet
    """
    p_attr, w_attr, _, specs = shift_lead(
        p_attr, w_attr, [], specs, func="write_pre_maet")
    w = w_attr
    from .show import show_pre_maet
    kwargs.pop("format", None)
    kwargs.pop("verbose", None)
    text = show_pre_maet(p_attr, w, specs, format="csv", verbose=False,
                         **kwargs)
    if destination is None:
        return text
    if hasattr(destination, "write"):
        destination.write(text)
        return text
    with open(destination, "w", newline="") as fh:
        fh.write(text)
    return text


def _levels(spec, key, default):
    v = spec.get(key, default)
    if np.isscalar(v) or isinstance(v, (bool, np.bool_)):
        return [v]
    return list(np.atleast_1d(v).ravel())


def _as_flag(v):
    if v is None:
        return None
    try:
        f = float(v)
    except (TypeError, ValueError):
        return None
    return float("nan") if np.isnan(f) else int(bool(f))
